# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
# /*---------------------------------------------------------------------------8
# |                                                                            |
# | Post processing
# |                                                                            |
# +------------------------------------4--------------------------------------*/

- name:                                "5.8 HANA Pacemaker Scaleout - Pause to give cluster time to stabilize"
  ansible.builtin.wait_for:
    timeout:                           "{{ cluster_status_report_wait_in_s }}"

- name:                                "5.8 HANA Pacemaker Scaleout - Check the post-provisioning cluster status"
  ansible.builtin.command:             "{{ cluster_status_cmd[ansible_os_family] }}"
  register:                            cluster_status_report
  changed_when:                        false
  failed_when:                         false

- name:                                "5.8 HANA Pacemaker Scaleout - Output cluster status"
  ansible.builtin.debug:
    msg:                               "{{ cluster_status_report.stdout }}"
    verbosity:                         2

- name:                                "5.8 HANA Pacemaker Scaleout - Check the SBD devices status"
  when:                                ansible_os_family | upper == 'SUSE'
  ansible.builtin.shell:               set -o pipefail && crm_mon -1 | grep sbd
  register:                            sbd_status_report
  changed_when:                        false
  failed_when:                         false


- name:                                "5.8 HANA Pacemaker Scaleout - Output SBD status"
  when:                                ansible_os_family | upper == 'SUSE'
  ansible.builtin.debug:
    msg:                               "{{ sbd_status_report.stdout }}"

- name:                                "5.8 HANA Pacemaker Scaleout - Pause to give HANA replication time to stabilize"
  ansible.builtin.wait_for:
    timeout:                           "{{ hsr_status_report_wait_in_s }}"

# Code block is specifically for ScaleOut, SUSE and RedHat
- name:                                "5.8 HANA Pacemaker Scaleout - Verify that the hook script is working as expected (Scale Out) for SUSE "
  when:
                                       - database_scale_out
                                       - ansible_os_family | upper == 'SUSE'
                                       - inventory_hostname == primary_instance_name
  block:
    - name:                            "5.8 HANA Pacemaker Scaleout - Verify the hook Installation (SUSE)"
      become_user:                     root
      become:                          true
      ansible.builtin.shell:           /usr/sbin/SAPHanaSR-showAttr
      register:                        outsaphanasr
      until:                           outsaphanasr.stdout | regex_search("(?s)\sSOK\s")
      retries:                         10
      delay:                           30
  rescue:
    - name:                            "[Rescue] 5.8 HANA Pacemaker Scaleout - Pause to give HANA replication time to stabilize"
      ansible.builtin.wait_for:
        timeout:                       "{{ rescue_hsr_status_report_wait_in_s }}"

    - name:                            "[Rescue] 5.8 HANA Pacemaker Scaleout - Verify the hook Installation (SUSE)"
      become_user:                     "{{ db_sid | lower }}adm"
      become:                          true
      ansible.builtin.shell: |
                                    set -o pipefail
                                    grep SAPHanaSr.*init nameserver_*.trc | tail -3
      args:
        chdir:                         /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/{{ inventory_hostname }}/trace
      register:                        saphanasr
      until:                           saphanasr.stdout is search("Running")
      retries:                         10
      delay:                           30

- name:                                "5.8 HANA Pacemaker Scaleout - Verify that the hook script is working as expected (Scale Out) for Red Hat {{ ansible_distribution_major_version }}"
  when:
                                       - ansible_os_family | upper == "REDHAT"
                                       - ansible_hostname == primary_instance_name
                                       - database_scale_out
  block:
    - name:                            "5.8 HANA Pacemaker Scaleout - Verify the hook Installation (REDHAT)"
      become_user:                     "{{ db_sid | lower }}adm"
      become:                          true
      ansible.builtin.shell: |
                                       set -o pipefail
                                       awk '/ha_dr_SAPHanaSR.*crm_attribute/ \
                                       { printf "%s %s %s %s\n",$2,$3,$5,$16 }' nameserver_*
      args:
        chdir:                         /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/{{ hostvars[primary_instance_name].virtual_host }}/trace
      register:                        saphanasr
      until:                           saphanasr.stdout is search("SOK")
      retries:                         10
      delay:                           30
  rescue:
    - name:                            "[Rescue] 5.8 HANA Pacemaker Scaleout - Pause to give HANA replication time to stabilize"
      ansible.builtin.wait_for:
        timeout:                       "{{ rescue_hsr_status_report_wait_in_s }}"

    - name:                            "[Rescue] 5.8 HANA Pacemaker Scaleout - Verify the hook Installation (REDHAT)"
      become_user:                     "{{ db_sid | lower }}adm"
      become:                          true
      ansible.builtin.shell: |
                                    set -o pipefail
                                    awk '/ha_dr_SAPHanaSR.*crm_attribute/ \
                                    { printf "%s %s %s %s\n",$2,$3,$5,$16 }' nameserver_*
      args:
        chdir:                         /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/{{ hostvars[primary_instance_name].virtual_host }}/trace
      register:                        saphanasr
      until:                           saphanasr.stdout is search("SOK")
      retries:                         10
      delay:                           30

- name:                                "5.8 HANA Pacemaker Scaleout - flag"
  ansible.builtin.file:
    path:                              /etc/sap_deployment_automation/sap_deployment_hana_pcm.txt
    state:                             touch
    mode:                              0755
