# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---

# sapcontrol EXITCODES

# /*---------------------------------------------------------------------------8
# |                                                                            |
# |     0  Last web method call successful
# |     1  Last web method call failed, invalid parameter
# |     2  StartWait, StopWait, WaitforStarted, WaitforStopped, RestartServiceWait
# |        timed out
# |        CheckSystemCertificates detected warnings
# |     3  GetProcessList succeeded, all processes running correctly
# |        CheckSystemCertificates detected errors
# |     4  GetProcessList succeeded, all processes stopped
# |                                                                            |
# +------------------------------------4--------------------------------------*/

- name:                                "Stop HANA on {{ ansible_hostname }}"
  become_user:                         "{{ db_sid | lower }}adm"
  become:                              true
  block:

    - name:                            "Determine if HANA is stopped on {{ ansible_hostname }}"
      ansible.builtin.shell:           "{{ sapcontrol_command }} -function GetProcessList"
      failed_when:                     false
      changed_when:                    false
      register:                        hana_stopped
      vars:
        allow_world_readable_tmpfiles:     true
      environment:
        PATH:                      /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}:/usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        DIR_LIBRARY:               /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        LD_LIBRARY_PATH:           /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        SAPSYSTEMNAME:             "{{ db_sid | upper }}"

    - name:                            "Ensure HANA is stopped {{ ansible_hostname }}"
      when:                            hana_stopped.rc != 4
      ansible.builtin.shell:           "{{ sapcontrol_command }} -function StopWait {{ hana_stop_start_timeout_in_seconds }} {{ hana_stop_start_delay_in_seconds }}"
      vars:
        allow_world_readable_tmpfiles:     true
      environment:
        PATH:                      /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}:/usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        DIR_LIBRARY:               /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        LD_LIBRARY_PATH:           /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        SAPSYSTEMNAME:             "{{ db_sid | upper }}"

    - name:                            "Verify HANA is stopped on {{ ansible_hostname }}"
      ansible.builtin.shell:           "{{ sapcontrol_command }} -function GetProcessList"
      changed_when:                    false
      register:                        hana_stopped
      failed_when:                     hana_stopped.rc != (4 or 0)
      vars:
        allow_world_readable_tmpfiles:     true
      environment:
        PATH:                      /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}:/usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        DIR_LIBRARY:               /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        LD_LIBRARY_PATH:           /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        SAPSYSTEMNAME:             "{{ db_sid | upper }}"
