# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
# +------------------------------------4--------------------------------------*/
# +                                                                           */
# +                                                                           */
# +            Set the environment variable as sourcing breaks                */
# +            when running from Azure DevOps                                 */
# +                                                                           */
# +------------------------------------4--------------------------------------*/

- name:                                "HANA HSR: - Add {{ db_sid | lower }}adm to sudoers"
  ansible.builtin.include_role:
    name:                              roles-os/1.11-accounts
    tasks_from:                        setup_hanausers_sudoers.yml

- name:                                "HANA HSR: - HSR Create helper variables"
  ansible.builtin.set_fact:
    DB:                                "{{ hana_tenant_database_name }}/HDB{{ db_instance_number }}"

- name:                                "HANA HSR: - pre-checks"
  block:
    - name:                            "HANA HSR: - pre-checks"
      ansible.builtin.import_tasks:    4.0.1.0-pre_checks.yml
      vars:
        allow_world_readable_tmpfiles:  true
      environment:
        PATH:                           /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}:/usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        DIR_LIBRARY:                    /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        LD_LIBRARY_PATH:                /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        SAPSYSTEMNAME:                  "{{ db_sid | upper }}"

- name:                                "HANA HSR: - Replication"
  block:

    - name:                            "HANA HSR: - HSR Set Runtime facts"
      ansible.builtin.import_tasks:    4.0.1.1-set_runtime_path_facts.yml
    - name:                            "HANA HSR: - Copy Keys"
      ansible.builtin.import_tasks:    4.0.1.3-copy_ssfs_keys.yml
    - name:                            "HANA HSR: - Create HANA backup"
      ansible.builtin.import_tasks:    4.0.1.4-create_hana_backup.yml

  vars:
    allow_world_readable_tmpfiles:     true
  environment:
    PATH:                              /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}:/usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
    DIR_LIBRARY:                       /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
    LD_LIBRARY_PATH:                   /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
    SAPSYSTEMNAME:                     "{{ db_sid | upper }}"
- name:                                "HANA HSR: - Provision replication"
  ansible.builtin.import_tasks:        4.0.1.5-provision_hana_replication.yml
  when:                                hana_system_replication_needed

- name:                                "HANA HSR: - Perform the HSR post check tasks"
  block:
    - name:                            "HANA HSR: - Perform the HSR post check tasks"
      ansible.builtin.import_tasks:    4.0.1.6-post_checks.yml
      vars:
        allow_world_readable_tmpfiles: true
      environment:
        PATH:                          /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}:/usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        DIR_LIBRARY:                   /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        LD_LIBRARY_PATH:               /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        SAPSYSTEMNAME:                 "{{ db_sid | upper }}"
  when:
    - hana_system_replication_needed
