---

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Test network connectivity to peer"
  ansible.builtin.wait_for:
    host:                              "{{ hostvars[item]['ansible_host'] }}"
    port:                              "{{ listener_port }}"
    timeout:                           10
  loop:                                 "{{ ansible_play_hosts_all }}"
  when:                                item != inventory_hostname
  delegate_to:                         localhost

- name:                                "4.1.3 Oracle Data Guard - Create ASM status SQL script"
  ansible.builtin.template:
    src:                               check_asm_status.j2
    dest:                              "/etc/sap_deployment_automation/dataguard_scripts/01_check_asm_status.sql"
    owner:                             "{{ grid_user_name }}"
    group:                             oinstall
    mode:                              '0644'

- name:                                "4.1.3 Oracle Data Guard - Check ASM status"
  become_user:                         "{{ grid_user_name }}"
  become:                              true
  ansible.builtin.shell: |
                                       setenv ORACLE_HOME /oracle/GRID/{{ ora_version }}
                                       setenv ORACLE_SID +ASM
                                       setenv PATH /oracle/GRID/{{ ora_version }}/bin:$PATH
                                       $ORACLE_HOME/bin/sqlplus / as sysasm @01_check_asm_status.sql
  register:                            asm_status
  changed_when:                        false
  args:
    chdir:                             "/etc/sap_deployment_automation/dataguard_scripts/"
    executable:                        /bin/csh

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: -Validate ASM diskgroups mounted"
  ansible.builtin.debug:
    var:                               asm_status

  when:
    - asm_status is defined

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: -Validate ASM diskgroups mounted"
  ansible.builtin.assert:
    that:                              "'MOUNTED' in asm_status.stdout"
    fail_msg:                          "ASM diskgroups not mounted"
  when:
    - asm_status is defined


...
