---

- name:                                "4.1.3 Oracle Data Guard -  Configure Data Guard parameters on primary SQL script"
  ansible.builtin.template:
    src:                               configure_data_guard_parameters_on_primary.j2
    dest:                              "/etc/sap_deployment_automation/dataguard_scripts/configure_data_guard_parameters_on_primary.sql"
    owner:                             "{{ oracle_user_name }}"
    group:                             oinstall
    mode:                              '0644'

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Configure Data Guard parameters on primary"
  become_user:                         "{{ oracle_user_name }}"
  become:                              true
  ansible.builtin.shell: |
                                       $ORACLE_HOME/bin/sqlplus / as sysdba @configure_data_guard_parameters_on_primary.sql
  register:                            dg_config
  failed_when:                         dg_config.rc != 0
  args:
    chdir:                             "/etc/sap_deployment_automation/dataguard_scripts/"
    executable:                        /bin/csh

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Show output from configure Data Guard parameters on primary"
  ansible.builtin.debug:
    var:                               dg_config.stdout_lines
    verbosity:                         2


- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Save output from configure Data Guard parameters on primary"
  ansible.builtin.copy:
    dest:                              /etc/sap_deployment_automation/dataguard_scripts/configure_data_guard_parameters_on_primary.log
    content:                           "{{ dg_config.stdout }}"
    mode:                              '0777'
  when:                                dg_config.stdout is defined

- name:                                "4.1.3 Oracle Data Guard -  Configure Check for standby redo logs on primary SQL script"
  ansible.builtin.template:
    src:                               configure_check_standby_redo_logs_on_primary.j2
    dest:                              "/etc/sap_deployment_automation/dataguard_scripts/configure_check_standby_redo_logs_on_primary.sql"
    owner:                             "{{ oracle_user_name }}"
    group:                             oinstall
    mode:                              '0644'


- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Check for standby redo logs on primary"
  become:                              true
  become_user:                         "{{ oracle_user_name }}"
  ansible.builtin.shell: |
                                       sqlplus -s / as sysdba @configure_check_standby_redo_logs_on_primary.sql
  register:                            srl_count
  changed_when:                        false
  args:
    chdir:                             "/etc/sap_deployment_automation/dataguard_scripts/"
    executable:                        /bin/csh

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Save output from check for standby redo logs on primary"
  ansible.builtin.debug:
    var:                               srl_count.stdout_lines

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Save output from Check for standby redo logs on primary"
  ansible.builtin.copy:
    dest:                              /etc/sap_deployment_automation/dataguard_scripts/configure_data_guard_parameters_on_primary.log
    content:                           "{{ srl_count.stdout }}"
    mode:                              '0777'
  when:                                srl_count.stdout is defined

- name:                                "4.1.3 Oracle Data Guard -  Configure Add standby redo logs on primary SQL script"
  ansible.builtin.template:
    src:                               configure_add_standby_redo_logs_on_primary.j2
    dest:                              "/etc/sap_deployment_automation/dataguard_scripts/configure_add_standby_redo_logs_on_primary.sql"
    owner:                             "{{ oracle_user_name }}"
    group:                             oinstall
    mode:                              '0644'

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Add standby redo logs on primary"
  when:
    - srl_count.stdout is defined
    - srl_count.stdout | trim | int == 0
  become:                              true
  become_user:                         "{{ oracle_user_name }}"
  ansible.builtin.shell: |
                                       sqlplus -s / as sysdba @configure_add_standby_redo_logs_on_primary.sql
  changed_when:                        false
  register:                            add_srl
  failed_when:                         add_srl.rc != 0
  args:
    chdir:                             "/etc/sap_deployment_automation/dataguard_scripts/"
    executable:                        /bin/csh

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Show output from Add standby redo logs on primary"
  ansible.builtin.debug:
    var:                               add_srl.stdout_lines
    verbosity:                         2

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Save output from Add standby redo logs on primary"
  ansible.builtin.copy:
    dest:                              /etc/sap_deployment_automation/dataguard_scripts/add_standby_redo_logs_on_primary.log
    content:                           "{{ add_srl.stdout }}"
    mode:                              '0777'
  when:                                add_srl.stdout is defined

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Deploy primary tnsnames.ora"
  ansible.builtin.template:
    src:                               tnsnames_primary.ora.j2
    dest:                              "/oracle/{{ db_sid | upper }}/{{ ora_version }}/network/admin/tnsnames.ora"
    owner:                             "{{ oracle_user_name }}"
    group:                             oinstall
    mode:                              '0644'

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Verify listener registration on primary"
  become:                              true
  become_user:                         "{{ grid_user_name }}"
  ansible.builtin.shell: |
                                       setenv ORACLE_HOME /oracle/GRID/{{ ora_version }}
                                       setenv ORACLE_SID +ASM
                                       setenv PATH /oracle/GRID/{{ ora_version }}/bin:$PATH
                                       lsnrctl services
  register:                            listener_check
  changed_when:                        false
  failed_when:                         listener_check.stdout is not search("Service {{ db_sid | upper }}")
  environment:
    ORACLE_HOME:                       "/oracle/GRID/{{ ora_version }}"
    ORACLE_SID:                        "{{ db_sid | upper }}"
  args:
    chdir:                             "/oracle/GRID/{{ ora_version }}/bin"

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Show listener registration on primary"
  ansible.builtin.debug:
    var:                               listener_check.stdout_lines
    verbosity:                         2


- name:                                "4.1.3 Oracle Data Guard: - Fail"
  ansible.builtin.fail:
    msg:                               "After 01-prepare-primary.yaml"


- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Register primary with listener if needed"
  when:                                listener_check.rc != 0
  become:                              true
  become_user:                         "{{ oracle_user_name }}"
  ansible.builtin.shell: |
    sqlplus -s / as sysdba <<EOF
    ALTER SYSTEM REGISTER;
    EXIT;
    EOF
  environment:
    ORACLE_HOME:                       "/oracle/{{ db_sid | upper }}/{{ ora_version }}"
    ORACLE_SID:                        "{{ db_sid | upper }}"
...
