---

# In dg_duplicate/tasks/main.yml

- name:                                "4.1.3 Oracle Data Guard - ASM - Check if standby already restored"
  when:                                node_tier == "oracle-asm"
  become_user:                         "{{ oracle_user_name }}"

  become:                              true
  ansible.builtin.shell: |
                                       setenv ORACLE_SID {{ db_sid | upper }}_STDBY
                                       /oracle/{{ db_sid | upper }}/{{ ora_version }}/bin/sqlplus -S / as sysdba <<EOF
                                       SET PAGESIZE 0 FEEDBACK OFF
                                       SELECT COUNT(*) FROM v\$datafile WHERE name LIKE '+DATA/{{ db_sid | upper }}_STDBY%';
                                       EXIT;
                                       EOF
  register:                            datafile_count
  args:
    chdir:                             "/etc/sap_deployment_automation/dataguard_scripts/"
    executable:                        /bin/csh
  changed_when:                        false
  failed_when:                         false

- name:                                "4.1.3 Oracle Data Guard - Check if standby already restored"
  when:                                node_tier == "oracle"
  become_user:                         "{{ oracle_user_name }}"

  become:                              true
  ansible.builtin.shell: |
                                       setenv ORACLE_SID {{ db_sid | upper }}_STDBY
                                       /oracle/{{ db_sid | upper }}/{{ ora_version }}/bin/sqlplus -S / as sysdba <<EOF
                                       SET PAGESIZE 0 FEEDBACK OFF
                                       SELECT COUNT(*) FROM v\$datafile;
                                       EXIT;
                                       EOF
  register:                            datafile_count
  args:
    chdir:                             "/etc/sap_deployment_automation/dataguard_scripts/"
    executable:                        /bin/csh
  changed_when:                        false
  failed_when:                         false

- name:                                "4.1.3 Oracle Data Guard - Check if rman already ran"
  ansible.builtin.set_fact:
    rman_duplicate_required:           "{%if not datafile_count.stdout is defined %}True{% else %} ((datafile_count.stdout | trim | int == 0) or (datafile_count.stdout is search('ORA-01507')) | bool) {% endif %}"

- name:                                "4.1.3 Oracle Data Guard - Prepare Secondary - Startup standby if not 'Running'"
  when:
    - datafile_count.stdout is defined
    - datafile_count.stdout is search('ORA-01034')
  block:
    - name:                            "4.1.3 Oracle Data Guard - Prepare Secondary - Start standby instance in NOMOUNT using PFile"
      become_user:                     "{{ oracle_user_name }}"
      become:                          true
      ansible.builtin.shell: |
                                       setenv ORACLE_SID {{ db_sid | upper }}_STDBY
                                       /oracle/{{ db_sid | upper }}/{{ ora_version }}/bin/sqlplus -s / as sysdba <<EOF
                                       STARTUP NOMOUNT PFILE='/oracle/{{ db_sid | upper }}/{{ ora_version }}/dbs/init{{ db_sid | upper }}_STDBY.ora';
                                       EXIT;
                                       EOF
      register:                        startup_result
      failed_when:                     startup_result.rc != 0
      args:
        chdir:                         "/etc/sap_deployment_automation/dataguard_scripts/"
        executable:                    /bin/csh

- name:                                "4.1.3 Oracle Data Guard - Show if rman run is required"
  ansible.builtin.debug:
    msg:
     - "SELECT COUNT(*) FROM v$datafile {{ datafile_count.stdout | default('not defined') }}"
     - "RMAN DUPLICATE required: {{ rman_duplicate_required }}"

- name:                                "4.1.3 Oracle Data Guard - Check if rman run is required"
  ansible.builtin.stat:
    path:                              /etc/sap_deployment_automation/dataguard_scripts/rman_duplicated.txt
  register:                            rman_duplicate_flag


- name:                                "4.1.3 Oracle Data Guard - Configure Data Guard"
  when:
    - rman_duplicate_required
    - not rman_duplicate_flag.stat.exists
  block:

    - name:                            "4.1.3 Oracle Data Guard - Execute RMAN DUPLICATE when using Oracle ASM"
      when:                            node_tier == "oracle-asm"
      become_user:                     "{{ oracle_user_name }}"
      become:                          true
      ansible.builtin.shell: |
                                      rman TARGET sys/'{{ main_password }}'@{{ db_sid | upper }} AUXILIARY sys/'{{ main_password }}'@{{ db_sid | upper }}_STDBY <<EOF
                                        RUN {
                                        DUPLICATE TARGET DATABASE FOR STANDBY FROM ACTIVE DATABASE
                                        DORECOVER
                                        NOFILENAMECHECK
                                        SPFILE
                                          SET DB_UNIQUE_NAME='{{ db_sid | upper }}_STDBY'
                                          SET FAL_SERVER='{{ db_sid | upper }}'
                                          SET FAL_CLIENT='{{ db_sid | upper }}_STDBY'
                                          SET STANDBY_FILE_MANAGEMENT='AUTO'
                                          SET LOG_ARCHIVE_CONFIG='DG_CONFIG=({{ db_sid | upper }},{{ db_sid | upper }}_STDBY)'
                                          SET LOG_ARCHIVE_DEST_1='LOCATION=USE_DB_RECOVERY_FILE_DEST VALID_FOR=(ALL_LOGFILES,ALL_ROLES) DB_UNIQUE_NAME={{ db_sid | upper }}_STDBY'
                                          SET LOG_ARCHIVE_DEST_2='SERVICE={{ db_sid | upper }} ASYNC VALID_FOR=(ONLINE_LOGFILES,PRIMARY_ROLE) DB_UNIQUE_NAME={{ db_sid | upper }}'
                                          SET CONTROL_FILES='+DATA/{{ db_sid | upper }}_STDBY/CONTROLFILE/control01.ctl','+FRA/{{ db_sid | upper }}_STDBY/CONTROLFILE/control02.ctl'
                                          SET DB_FILE_NAME_CONVERT='+DATA/{{ db_sid | upper }}/','+DATA/{{ db_sid | upper }}_STDBY/'
                                          SET LOG_FILE_NAME_CONVERT='+DATA/{{ db_sid | upper }}/','+DATA/{{ db_sid | upper }}_STDBY/','+RECO/{{ db_sid | upper }}/','+ARCH/{{ db_sid | upper }}_STDBY/';                                        EXIT;
                                        EOF
      args:
        chdir:                         "/etc/sap_deployment_automation/dataguard_scripts/"
        executable:                    /bin/csh
        creates:                       /etc/sap_deployment_automation/dataguard_scripts/rman_duplicated.txt
      register:                        rman_duplicate
      failed_when:                     rman_duplicate.rc != 0

    - name:                            "4.1.3 Oracle Data Guard - Execute RMAN DUPLICATE when using Oracle"
      when:                            node_tier == "oracle"
      become_user:                     "{{ oracle_user_name }}"
      become:                          true
      ansible.builtin.shell: |
                                       rman TARGET sys/'{{ main_password }}'@{{ db_sid | upper }} AUXILIARY sys/'{{ main_password }}'@{{ db_sid | upper }}_STDBY <<EOF
                                        RUN {

                                        DUPLICATE TARGET DATABASE FOR STANDBY FROM ACTIVE DATABASE
                                        SPFILE
                                          SET db_name='{{ db_sid | upper }}'
                                          SET db_unique_name='{{ db_sid | upper }}_STDBY'
                                          SET fal_server='{{ db_sid | upper }}'
                                          SET standby_file_management='AUTO'
                                          SET db_recovery_file_dest='/oracle/{{ db_sid | upper }}/oraarch/'
                                          SET control_files='/oracle/{{ db_sid | upper }}/{{ ora_version }}/dbs/cntrl{{ db_sid | upper }}_STDBY.dbf'
                                        DORECOVER
                                        NOFILENAMECHECK;
                                        }
                                       EXIT;
                                       EOF
      args:
        chdir:                         "/etc/sap_deployment_automation/dataguard_scripts/"
        executable:                    /bin/csh
        creates:                       /etc/sap_deployment_automation/dataguard_scripts/rman_duplicated.txt
      register:                        rman_duplicate
      failed_when:                     rman_duplicate.rc != 0

    - name:                            "4.1.3 Oracle Data Guard - Show Execute RMAN DUPLICATE output"
      ansible.builtin.debug:
        msg:                           "RMAN results: {{ rman_duplicate.stdout }}"
      when:                            rman_duplicate.stdout is defined

    - name:                            "4.1.3 Oracle Data Guard - Save RMAN log"
      ansible.builtin.copy:
        dest:                          /etc/sap_deployment_automation/dataguard_scripts/rman_duplicate_{{ ansible_date_time.epoch }}.log
        content:                       "{{ rman_duplicate.stdout }}"
        mode:                          '0777'
      when:                            rman_duplicate.stdout is defined

    - name:                            "4.1.3 Oracle Data Guard - Verify DUPLICATE completion"
      ansible.builtin.assert:
        that:                          "'Finished Duplicate Db' in rman_duplicate.stdout"
        fail_msg:                      "RMAN DUPLICATE did not complete successfully"

    - name:                            "4.1.3 Oracle Data Guard - Create rman flag file to indicate successful duplicate"
      ansible.builtin.file:
        path:                          /etc/sap_deployment_automation/dataguard_scripts/rman_duplicated.txt
        state:                         touch
        mode:                          '0644'
        owner:                         "{{ oracle_user_name }}"
        group:                         oinstall
      when:
        - rman_duplicate.rc is defined
        - rman_duplicate.rc == 0

    - name:                            "4.1.3 Oracle Data Guard - Check standby database mounted"
      become_user:                     "{{ oracle_user_name }}"
      become:                          true
      ansible.builtin.shell: |
                                       setenv ORACLE_SID {{ db_sid | upper }}_STDBY
                                       $ORACLE_HOME/bin/sqlplus -s / as sysdba <<EOF
                                       SET PAGESIZE 0 FEEDBACK OFF
                                       SELECT database_role || ':' || open_mode FROM v\$database;
                                       EXIT;
                                       EOF

      register:                        db_status
      changed_when:                    false
      failed_when:                     "'PHYSICAL STANDBY:MOUNTED' not in db_status.stdout"
      args:
        chdir:                         "/etc/sap_deployment_automation/dataguard_scripts/"
        executable:                    /bin/csh

    - name:                            "4.1.3 Oracle Data Guard - Secondary: - Show Check standby database mounted output"
      ansible.builtin.debug:
        msg:                           "Database mount information: {{ db_status.stdout }}"
        verbosity:                     2

    - name:                            "4.1.3 Oracle Data Guard - Secondary: - Save Check standby database mounted"
      ansible.builtin.copy:
        dest:                          /etc/sap_deployment_automation/dataguard_scripts/check_standby_database_mounted_{{ ansible_date_time.epoch }}.log
        content:                       "{{ db_status.stdout }}"
        mode:                          '0777'
      when:                            db_status.stdout is defined

    - name:                            "4.1.3 Oracle Data Guard - Set Data Guard configuration status"
      ansible.builtin.set_fact:
        secondary_dg_configured:       "{{ 'PHYSICAL STANDBY:MOUNTED' in db_status.stdout }}"

    - name:                            "4.1.3 Oracle Data Guard - Display Data Guard status"
      ansible.builtin.debug:
        msg:
          - "Database instance:        {{ ansible_hostname }}"
          - "Data guard configured:    {{ secondary_dg_configured }}"

    - name:                            "4.1.3 Oracle Data Guard - Secondary - Enable Flashback on Oracle Secondary DB"
      become:                          true
      become_user:                     "{{ oracle_user_name }}"
      ansible.builtin.shell: |
                                       setenv ORACLE_SID {{ db_sid | upper }}_STDBY
                                       sqlplus -s / as sysdba << EOF
                                       WHENEVER SQLERROR EXIT SQL.SQLCODE
                                       ALTER DATABASE FLASHBACK ON;
                                       exit
                                       EOF
      environment:
        ORACLE_SID:                    "{{ db_sid | upper }}_STDBY"
        ORACLE_HOME:                   "/oracle/{{ db_sid | upper }}/{{ ora_version }}"
      args:
        executable:                    /bin/csh
      register:                        flashback_secondary
      failed_when:                     flashback_secondary.rc != 0
      changed_when:                    flashback_secondary.rc == 0

    - name:                            "4.1.3 Oracle Data Guard - Secondary - Enable Flashback on Oracle Secondary DB"
      become:                          true
      become_user:                     "{{ oracle_user_name }}"
      ansible.builtin.shell: |
                                       setenv ORACLE_SID {{ db_sid | upper }}_STDBY
                                       sqlplus -s / as sysdba << EOF
                                       WHENEVER SQLERROR EXIT SQL.SQLCODE
                                       ALTER SYSTEM SET DG_BROKER_START = true;
                                       exit
                                       EOF
      environment:
        ORACLE_SID:                    "{{ db_sid | upper }}_STDBY"
        ORACLE_HOME:                   "/oracle/{{ db_sid | upper }}/{{ ora_release }}"
      args:
        executable:                    /bin/csh
      failed_when:                     flashback_secondary.rc != 0
      changed_when:                    flashback_secondary.rc == 0
