---


# In dg_duplicate/tasks/main.yml

- name:                                "4.1.3 Oracle Data Guard - Check if standby already restored"
  become_user:                         "{{ oracle_user_name }}"
  become:                              true
  ansible.builtin.shell: |
                                       setenv ORACLE_SID {{ db_sid | upper }}_STDBY
                                       /oracle/{{ db_sid | upper }}/{{ ora_version }}/bin/sqlplus -S / as <<EOF
                                       SET PAGESIZE 0 FEEDBACK OFF
                                       SELECT COUNT(*) FROM v\$datafile WHERE name LIKE '+DATA/{{ db_sid | upper }}_STDBY%';
                                       EXIT;
                                       EOF
  register:                            datafile_count
  args:
    chdir:                             "/etc/sap_deployment_automation/dataguard_scripts/"
    executable:                        /bin/csh
  changed_when:                        false
  failed_when:                         false

- name:                                "4.1.3 Oracle Data Guard - Execute RMAN DUPLICATE if not already done flag"
  ansible.builtin.set_fact:
    rman_duplicate_required:           "{{ datafile_count.stdout | trim | int == 0 }}"

- name:                                "4.1.3 Oracle Data Guard - Execute RMAN DUPLICATE if not already done flag"
  ansible.builtin.debug:
    msg:                               "RMAN DUPLICATE required: {{ rman_duplicate_required }} (datafile count: {{ datafile_count.stdout | trim }})"

- name:                                "4.1.3 Oracle Data Guard - Configure Data Guard"
  when:
    - rman_duplicate_required
  block:
    - name:                            "4.1.3 Oracle Data Guard -  Configure RMAN DUPLICATE script"
      ansible.builtin.template:
        src:                           rman-restore.rman.j2
        dest:                          "/etc/sap_deployment_automation/dataguard_scripts/rman-restore.rman"
        owner:                         "{{ oracle_user_name }}"
        group:                         oinstall
        mode:                          '0644'

    - name:                            "4.1.3 Oracle Data Guard - Execute RMAN DUPLICATE"
      become_user:                     "{{ oracle_user_name }}"
      become:                          true
      ansible.builtin.shell: |
                                       rman TARGET sys/{{ main_password }}@{{ db_sid | upper }} AUXILIARY sys/{{ main_password }}@{{ db_sid | upper }}_STDBY @rman-restore.rman
      args:
        chdir:                         "/etc/sap_deployment_automation/dataguard_scripts/"
        executable:                    /bin/csh
        creates:                       /etc/sap_deployment_automation/dataguard_scripts/rman-restore.txt
      register:                        rman_duplicate
      failed_when:                     rman_duplicate.rc != 0

    - name:                            "4.1.3 Oracle Data Guard - Save RMAN flag file"
      ansible.builtin.file:
        path:                          /etc/sap_deployment_automation/dataguard_scripts/rman-restore.txt
        state:                         touch
        owner:                         "{{ oracle_user_name }}"
        group:                         oinstall
        mode:                          '0777'
      when:
      - rman_duplicate.stdout is defined
      - rman_duplicate.rc == 0

    - name:                            "4.1.3 Oracle Data Guard - Setup Primary: - Show Execute RMAN DUPLICATE output"
      ansible.builtin.debug:
        var:                           job_result.stdout
        verbosity:                     2
      when:                            job_result.stdout is defined

    - name:                            "4.1.3 Oracle Data Guard - Save RMAN log"
      ansible.builtin.copy:
        dest:                          /etc/sap_deployment_automation/dataguard_scripts/rman_duplicate_{{ ansible_date_time.epoch }}.log
        content:                       "{{ job_result.stdout }}"
        mode:                          '0777'
      when:                            job_result.stdout is defined


    - name:                            "4.1.3 Oracle Data Guard - Verify DUPLICATE completion"
      ansible.builtin.assert:
        that:                          "'Finished Duplicate Db' in job_result.stdout"
        fail_msg:                      "RMAN DUPLICATE did not complete successfully"

    - name:                            "4.1.3 Oracle Data Guard - Check standby database mounted"
      become_user:                     "{{ oracle_user_name }}"
      become:                          true
      ansible.builtin.shell: |
                                       setenv ORACLE_SID {{ db_sid | upper }}_STDBY
                                       $ORACLE_HOME/bin/sqlplus -s / as sysdba <<EOF
                                       SET PAGESIZE 0 FEEDBACK OFF
                                       SELECT database_role || ':' || open_mode FROM v\$database;
                                       EXIT;
                                       EOF

      register:                        db_status
      changed_when:                    false
      failed_when:                     "'PHYSICAL STANDBY:MOUNTED' not in db_status.stdout"
      args:
        chdir:                         "/etc/sap_deployment_automation/dataguard_scripts/"
        executable:                    /bin/csh

    - name:                            "4.1.3 Oracle Data Guard - Setup Primary: - Show Check standby database mounted output"
      ansible.builtin.debug:
        var:                           db_status.stdout_lines
        verbosity:                     2

    - name:                            "4.1.3 Oracle Data Guard - Save Check standby database mounted"
      ansible.builtin.copy:
        dest:                          /etc/sap_deployment_automation/dataguard_scripts/check_standby_database_mounted_{{ ansible_date_time.epoch }}.log
        content:                       "{{ db_status.stdout }}"
        mode:                          '0777'
      when:                            db_status.stdout is defined
