---

- name:                                "4.1.3 Oracle Data Guard -  Configure standby Data Guard"
  when:                                ansible_hostname == ora_secondary
  block:
    - name:                            "4.1.3 Oracle Data Guard -  Configure standby Data Guard parameters SQL script"
      ansible.builtin.template:
        src:                           configure_data_guard_standby_instance.sql.j2
        dest:                          "/etc/sap_deployment_automation/dataguard_scripts/configure_data_guard_standby_instance.sql"
        owner:                         "{{ oracle_user_name }}"
        group:                         oinstall
        mode:                          '0644'

    - name:                            "4.1.3 Oracle Data Guard -  Configure standby Data Guard parameters"
      become_user:                     "{{ oracle_user_name }}"
      become:                          true
      ansible.builtin.shell: |
                                       setenv ORACLE_SID={{ db_sid | upper }}_STDBY
                                       $ORACLE_HOME/bin/sqlplus -s / as sysdba @configure_data_guard_standby_instance.sql
      register:                        standby_config
      failed_when:                     standby_config.rc != 0
      args:
        chdir:                         "/etc/sap_deployment_automation/dataguard_scripts/"
        executable:                    /bin/csh

    - name:                            "4.1.3 Oracle Data Guard - Setup Primary: - Show Configure standby Data Guard parameters"
      ansible.builtin.debug:
        var:                           standby_config.stdout_lines
        verbosity:                     2

    - name:                            "4.1.3 Oracle Data Guard - Save configure standby Data Guard parameters"
      ansible.builtin.copy:
        dest:                          "/etc/sap_deployment_automation/dataguard_scripts/configure_data_guard_standby_{{ ansible_date_time.epoch }}.log"
        content:                       "{{ standby_config.stdout }}"
        mode:                          '0777'
      when:                            standby_config.stdout is defined

    - name:                            "4.1.3 Oracle Data Guard -  Configure restart standby SQL script"
      ansible.builtin.template:
        src:                           restart_standby.sql.j2
        dest:                          "/etc/sap_deployment_automation/dataguard_scripts/restart_standby.sql"
        owner:                         "{{ oracle_user_name }}"
        group:                         oinstall
        mode:                          '0644'

    - name:                            "4.1.3 Oracle Data Guard -  Configure restart standby"
      become_user:                     "{{ oracle_user_name }}"
      become:                          true
      ansible.builtin.shell: |
                                       setenv ORACLE_SID={{ db_sid | upper }}_STDBY
                                       $ORACLE_HOME/bin/sqlplus -s / as sysdba @restart_standby.sql
      register:                        standby_restart
      failed_when:                     standby_restart.rc != 0
      args:
        chdir:                         "/etc/sap_deployment_automation/dataguard_scripts/"
        executable:                    /bin/csh

    - name:                            "4.1.3 Oracle Data Guard - Setup Primary: - Show Configure restart standby dg_status results"
      ansible.builtin.debug:
        var:                           standby_restart.stdout_lines
        verbosity:                     2

    - name:                            "4.1.3 Oracle Data Guard - Save configure restart standby results"
      ansible.builtin.copy:
        dest:                          /etc/sap_deployment_automation/dataguard_scripts/restart_standby_{{ ansible_date_time.epoch }}.log
        content:                       "{{ standby_restart.stdout }}"
        mode:                          '0777'
      when:                            standby_restart.stdout is defined

    - name:                            "4.1.3 Oracle Data Guard -  Configure check standby redo logs SQL script"
      ansible.builtin.template:
        src:                           check_standby_redo_logs.sql.j2
        dest:                          "/etc/sap_deployment_automation/dataguard_scripts/check_standby_redo_logs.sql"
        owner:                         "{{ oracle_user_name }}"
        group:                         oinstall
        mode:                          '0644'

    - name:                            "4.1.3 Oracle Data Guard - Configure check standby redo logs"
      become_user:                     "{{ oracle_user_name }}"
      become:                          true
      ansible.builtin.shell: |
                                       setenv ORACLE_SID={{ db_sid | upper }}_STDBY
                                       $ORACLE_HOME/bin/sqlplus -s / as sysdba @check_standby_redo_logs.sql
      register:                        srl_count
      failed_when:                     false
      args:
        chdir:                             "/etc/sap_deployment_automation/dataguard_scripts/"
        executable:                        /bin/csh

    - name:                            "4.1.3 Oracle Data Guard - Setup Primary: - Show Configure check standby redo logs results"
      ansible.builtin.debug:
        var:                           srl_count.stdout_lines
        verbosity:                         2

    - name:                            "4.1.3 Oracle Data Guard - Save configure check standby redo logs results"
      ansible.builtin.copy:
        dest:                          /etc/sap_deployment_automation/dataguard_scripts/restart_standby_{{ ansible_date_time.epoch }}.log
        content:                       "{{ srl_count.stdout }}"
        mode:                          '0777'
      when:                            srl_count.stdout is defined


    - name:                            "4.1.3 Oracle Data Guard -  Configure check standby redo logs SQL script"
      ansible.builtin.template:
        src:                           check_standby_redo_logs.sql.j2
        dest:                          "/etc/sap_deployment_automation/dataguard_scripts/check_standby_redo_logs.sql"
        owner:                         "{{ oracle_user_name }}"
        group:                         oinstall
        mode:                          '0644'

    - name:                            "4.1.3 Oracle Data Guard - Configure check standby redo logs"
      become_user:                     "{{ oracle_user_name }}"
      become:                          true
      ansible.builtin.shell: |
                                       setenv ORACLE_SID={{ db_sid | upper }}_STDBY
                                       $ORACLE_HOME/bin/sqlplus -s / as sysdba @check_standby_redo_logs.sql
      register:                        srl_count
      failed_when:                     false
      args:
        chdir:                         "/etc/sap_deployment_automation/dataguard_scripts/"
        executable:                    /bin/csh

    - name:                            "4.1.3 Oracle Data Guard - Setup Primary: - Show Configure check standby redo logs results"
      ansible.builtin.debug:
        var:                           srl_count.stdout_lines
        verbosity:                     2

    - name:                            "4.1.3 Oracle Data Guard - Save configure check standby redo logs results"
      ansible.builtin.copy:
        dest:                          /etc/sap_deployment_automation/dataguard_scripts/restart_standby_{{ ansible_date_time.epoch }}.log
        content:                       "{{ srl_count.stdout }}"
        mode:                          '0777'
      when:                            srl_count.stdout is defined


    - name:                            "4.1.3 Oracle Data Guard -  Configure add standby redo logs SQL script"
      ansible.builtin.template:
        src:                           add_standby_redo_logs.sql.j2
        dest:                          "/etc/sap_deployment_automation/dataguard_scripts/add_standby_redo_logs.sql"
        owner:                         "{{ oracle_user_name }}"
        group:                         oinstall
        mode:                          '0644'

    - name:                            "4.1.3 Oracle Data Guard - Add standby redo logs"
      become_user:                     "{{ oracle_user_name }}"
      become:                          true
      when:
        - srl_count.stdout | trim | int == 0
      ansible.builtin.shell: |
                                       setenv ORACLE_SID={{ db_sid | upper }}_STDBY
                                       $ORACLE_HOME/bin/sqlplus -s / as sysdba @add_standby_redo_logs.sql
      register:                        add_srl_standby
      failed_when:                     add_srl_standby.rc != 0
      args:
        chdir:                         "/etc/sap_deployment_automation/dataguard_scripts/"
        executable:                    /bin/csh

    - name:                            "4.1.3 Oracle Data Guard - Setup Primary: - Show add standby redo logs results"
      ansible.builtin.debug:
        var:                           add_srl_standby.stdout_lines
        verbosity:                     2

    - name:                            "4.1.3 Oracle Data Guard - Save add standby redo logs results"
      ansible.builtin.copy:
        dest:                          /etc/sap_deployment_automation/dataguard_scripts/add_standby_redo_logs{{ ansible_date_time.epoch }}.log
        content:                       "{{ add_srl_standby.stdout }}"
        mode:                          '0777'
      when:                            add_srl_standby.stdout is defined

- name:                                "4.1.3 Oracle Data Guard -  Configure standby Data Guard"
  when:                                ansible_hostname == ora_primary
  block:

    - name:                            "4.1.3 Oracle Data Guard -  Configure enable log shipping on primary SQL script"
      ansible.builtin.template:
        src:                           enable_log_shipping_on_primary.sql.j2
        dest:                          "/etc/sap_deployment_automation/dataguard_scripts/enable_log_shipping_on_primary.sql"
        owner:                         "{{ oracle_user_name }}"
        group:                         oinstall
        mode:                          '0644'

    - name:                            "4.1.3 Oracle Data Guard - Enable log shipping on primary"
      become_user:                     "{{ oracle_user_name }}"
      become:                          true
      ansible.builtin.shell: |
                                       $ORACLE_HOME/bin/sqlplus -s / as sysdba @enable_log_shipping_on_primary.sql
      register:                        enable_shipping
      failed_when:                     enable_shipping.rc != 0
      args:
        chdir:                         "/etc/sap_deployment_automation/dataguard_scripts/"
        executable:                    /bin/csh

    - name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Show enable log shipping on primary"
      ansible.builtin.debug:
        var:                           enable_shipping.stdout_lines
        verbosity:                     2

    - name:                                "4.1.3 Oracle Data Guard - Save enable log shipping on primary results"
      ansible.builtin.copy:
        dest:                          /etc/sap_deployment_automation/dataguard_scripts/enable_shipping_{{ ansible_date_time.epoch }}.log
        content:                       "{{ enable_shipping.stdout }}"
        mode:                          '0777'
      when:                            enable_shipping.stdout is defined

- name:                                "4.1.3 Oracle Data Guard -  Start managed recovery on standby"
  when:                                ansible_hostname == ora_secondary
  block:

    - name:                            "4.1.3 Oracle Data Guard - Configure start managed recovery on standby SQL script"
      ansible.builtin.template:
        src:                           start_managed_recovery_on_standby.sql.j2
        dest:                          "/etc/sap_deployment_automation/dataguard_scripts/start_managed_recovery_on_standby.sql"
        owner:                         "{{ oracle_user_name }}"
        group:                         oinstall
        mode:                          '0644'

    - name:                            "4.1.3 Oracle Data Guard - Start managed recovery on standby"
      become_user:                     "{{ oracle_user_name }}"
      become:                          true
      ansible.builtin.shell: |
                                       $ORACLE_HOME/bin/sqlplus -s / as sysdba @start_managed_recovery_on_standby.sql
      register:                        start_recovery
      failed_when:                     start_recovery.rc != 0
      args:
        chdir:                         "/etc/sap_deployment_automation/dataguard_scripts/"
        executable:                    /bin/csh

    - name:                            "4.1.3 Oracle Data Guard - Setup Primary: - Show managed recovery on standby results"
      ansible.builtin.debug:
        var:                           start_recovery.stdout_lines
        verbosity:                     2

    - name:                            "4.1.3 Oracle Data Guard - Save start managed recovery on standby results"
      ansible.builtin.copy:
        dest:                          /etc/sap_deployment_automation/dataguard_scripts/start_managed_recovery_on_standby{{ ansible_date_time.epoch }}.log
        content:                       "{{ start_recovery.stdout }}"
        mode:                          '0777'
      when:                            start_recovery.stdout is defined


- name:                                "4.1.3 Oracle Data Guard - Verify Data Guard configuration"
  when:                                ansible_hostname == ora_primary
  block:
    - name:                            "4.1.3 Oracle Data Guard - Configure verify Data Guard configuration SQL script"
      ansible.builtin.template:
        src:                           verify_data_guard_configuration.sql.j2
        dest:                          "/etc/sap_deployment_automation/dataguard_scripts/verify_data_guard_configuration.sql"
        owner:                         "{{ oracle_user_name }}"
        group:                         oinstall
        mode:                          '0644'


    - name:                            "4.1.3 Oracle Data Guard - Wait for MRP to start"
      ansible.builtin.pause:
        seconds:                       10

    - name:                            "4.1.3 Oracle Data Guard - Verify Data Guard configuration"
      become_user:                     "{{ oracle_user_name }}"
      become:                          true
      ansible.builtin.shell: |
                                      setenv ORACLE_SID {{ item.sid }}
                                      $ORACLE_HOME/bin/sqlplus -s / as sysdba @verify_data_guard_configuration.sql
      loop:
        - { sid: "{{ db_sid | upper }}", host: "primary" }
        - { sid: "{{ db_sid | upper }}_STDBY", host: "standby" }
      register:                        dg_status
      changed_when:                    false

    - name:                            "4.1.3 Oracle Data Guard - Display Data Guard status"
      ansible.builtin.debug:
        msg:                           "{{ item.stdout_lines }}"
      loop:                            "{{ dg_status.results }}"
      when:                            item.skipped is not defined
