---

- name:                                "4.1.3 Oracle Data Guard - Post deployment tasks on Primary - Enable log shipping on primary"
  become_user:                         "{{ oracle_user_name }}"
  become:                              true
  ansible.builtin.shell: |
                                       setenv ORACLE_SID {{ db_sid | upper }}
                                       $ORACLE_HOME/bin/sqlplus -s / as sysdba <<EOF
                                       WHENEVER SQLERROR EXIT SQL.SQLCODE
                                       ALTER SYSTEM SET LOG_ARCHIVE_DEST_2='SERVICE={{ db_sid | upper }}_STDBY ASYNC VALID_FOR=(ONLINE_LOGFILES,PRIMARY_ROLE) DB_UNIQUE_NAME={{ db_sid | upper }}_STDBY' SCOPE=BOTH;
                                       ALTER SYSTEM SET LOG_ARCHIVE_DEST_STATE_2='ENABLE' SCOPE=BOTH;
                                       ALTER SYSTEM SWITCH LOGFILE;
                                       ALTER SYSTEM SWITCH LOGFILE;
                                       ALTER SYSTEM SET DG_BROKER_START = true;
                                       EXIT;
                                       EOF
  register:                            enable_shipping
  failed_when:                         enable_shipping.rc != 0
  args:
    chdir:                             "/etc/sap_deployment_automation/dataguard_scripts/"
    executable:                        /bin/csh

- name:                                "4.1.3 Oracle Data Guard - Post deployment tasks on Primary - Show enable log shipping on primary"
  ansible.builtin.debug:
    var:                               enable_shipping.stdout_lines
    verbosity:                         2

- name:                                "4.1.3 Oracle Data Guard - Post deployment tasks on Primary - Save enable log shipping on primary results"
  ansible.builtin.copy:
    dest:                              /etc/sap_deployment_automation/dataguard_scripts/enable_shipping_{{ ansible_date_time.epoch }}.log
    content:                           "{{ enable_shipping.stdout }}"
    mode:                              '0777'
  when:                                enable_shipping.stdout is defined

- name:                                "4.1.3 Oracle Data Guard - Post deployment tasks on Primary - Verify Data Guard configuration"
  when:                                ansible_hostname == ora_primary
  block:

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Check if database is open on Primary"
      become:                          true
      become_user:                     "{{ oracle_user_name }}"
      ansible.builtin.shell: |
                                       sqlplus -s / as sysdba << EOF
                                       SET HEADING OFF
                                       SET FEEDBACK OFF
                                       SELECT open_mode FROM v\$database;
                                       EXIT;
                                       EOF
      environment:
        ORACLE_SID:                    "{{ db_sid | upper }}"
        ORACLE_HOME:                   "/oracle/{{ db_sid | upper }}/{{ ora_version }}"
      args:
        executable:                    /bin/csh
      register:                        primary_open_mode
      failed_when:                     "'READ WRITE' not in primary_open_mode.stdout"
      changed_when:                    false

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Ensure database is open on Primary"
      become:                          true
      become_user:                     "{{ oracle_user_name }}"
      ansible.builtin.shell: |
                                       sqlplus -s / as sysdba << EOF
                                       ALTER DATABASE OPEN;
                                       EXIT;
                                       EOF
      environment:
        ORACLE_SID:                    "{{ db_sid | upper }}"
        ORACLE_HOME:                   "/oracle/{{ db_sid | upper }}/{{ ora_version }}"
      args:
        executable:                    /bin/csh
      when:                            "'READ WRITE' not in primary_open_mode.stdout"
      register:                        open_primary
      failed_when:                     open_primary.rc != 0 and 'ORA-01531' not in open_primary.stderr

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Check if Data Guard Broker configuration exists on Primary"
      become:                          true
      become_user:                     "{{ oracle_user_name }}"
      ansible.builtin.shell: |
                                       dgmgrl / as sysdba << EOF
                                       SHOW CONFIGURATION
                                       EOF
      failed_when:                     false
      changed_when:                    false
      register:                        dgconfig_check
      args:
        executable:                    /bin/csh

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Create Data Guard Configuration on Primary"
      when:                            "'ORA-16532' in dgconfig_check.stdout or 'ORA-16596' in dgconfig_check.stdout"
      # ORA-16532: Oracle Data Guard broker configuration does not exist
      # ORA-16596: member not part of the Oracle Data Guard broker configuration
      become:                          true
      become_user:                     "{{ oracle_user_name }}"
      ansible.builtin.shell: |
                                       dgmgrl / as sysdba << EOF
                                       CREATE CONFIGURATION {{ db_sid | upper }}_dg_config AS PRIMARY DATABASE IS {{ db_sid | upper }} CONNECT IDENTIFIER IS {{ db_sid | upper }};
                                       exit;
                                       EOF
      register:                        dgconfig_results
      failed_when:                     dgconfig_results.rc > 0
      args:
        executable:                    /bin/csh

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Update Data Guard Configuration on Primary Add Secondary "
      become:                          true
      become_user:                     "{{ oracle_user_name }}"
      ansible.builtin.shell: |
                                       dgmgrl / as sysdba << EOF
                                       ADD DATABASE {{ db_sid | upper }}_STDBY AS CONNECT IDENTIFIER IS {{ db_sid | upper }}_STDBY MAINTAINED AS PHYSICAL;
                                       ENABLE CONFIGURATION;
                                       exit;
                                       EOF
      register:                        dgconfig_secondary_results
      failed_when:                     dgconfig_secondary_results.rc > 0
      args:
        executable:                    /bin/csh

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Enable Fast-Start Failover"
      become:                          true
      become_user:                     "{{ oracle_user_name }}"
      ansible.builtin.shell: |
                                       dgmgrl / as sysdba << EOF
                                       EDIT DATABASE {{ db_sid | upper }} SET PROPERTY 'LogXptMode'='SYNC';
                                       EDIT DATABASE {{ db_sid | upper }}_STDBY SET PROPERTY 'LogXptMode'='SYNC';
                                       EDIT CONFIGURATION SET PROTECTION MODE AS MAXAVAILABILITY;
                                       exit;
                                       EOF
      register:                        dgconfig_fast_start_results
      failed_when:                     dgconfig_fast_start_results.rc > 0
      args:
        executable:                    /bin/csh

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Enable Data Guard Broker on Primary"
      become:                          true
      become_user:                     "{{ oracle_user_name }}"
      ansible.builtin.shell: |
                                       sqlplus -s / as sysdba << EOF
                                       ALTER SYSTEM SET dg_broker_start=true;
                                       EXIT;
                                       EOF
      register:                        dg_broker_primary_results
      failed_when:                     dg_broker_primary_results.rc > 0
      args:
        executable:                    /bin/csh

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Create HA Service on Primary"
      become:                          true
      become_user:                     "{{ oracle_user_name }}"
      ansible.builtin.shell: |
                                       sqlplus -s / as sysdba << EOF

                                       EXEC DBMS_SERVICE.CREATE_SERVICE(service_name=>'{{ db_sid | upper }}_HA',network_name=>'{{ db_sid | upper }}_HA');
                                       EXEC DBMS_SERVICE.START_SERVICE('{{ db_sid | upper }}_HA');
                                       EXIT;
                                       EOF
      register:                        dg_broker_primary_results
      failed_when:                     dg_broker_primary_results.rc > 0
      args:
        executable:                    /bin/csh

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Create Database Trigger"
      become:                          true
      become_user:                     "{{ oracle_user_name }}"
      ansible.builtin.shell: |
                                       sqlplus -s / as sysdba << EOF

                                       CREATE OR REPLACE TRIGGER {{ db_sid | lower }}_HA_SERVICE
                                         after startup on database
                                         DECLARE
                                         role VARCHAR(30);
                                         BEGIN
                                           SELECT DATABASE_ROLE INTO role FROM V\$DATABASE;
                                           IF role = 'PRIMARY' THEN
                                             DBMS_SERVICE.START_SERVICE('{{ db_sid | upper }}_HA');
                                           END IF;
                                         END;
                                       /
                                       EXIT;
                                       EOF
      register:                        dg_broker_primary_results
      failed_when:                     dg_broker_primary_results.rc > 0
      args:
        executable:                    /bin/csh

# Disable the automatic restart for database on Primary.
- name:                                "4.1.3 Oracle Data Guard - Primary - Post Processing: Check if database registered with restart on Primary"
  become:                              true
  become_user:                         "{{ oracle_user_name }}"
  ansible.builtin.shell: |
                                       setenv ORACLE_SID {{ db_sid | upper }}
                                       srvctl config database -d {{ db_sid | upper }}
  environment:
    ORACLE_HOME:                       "/oracle/{{ db_sid | upper }}/{{ ora_version }}"
    PATH:                              "/oracle/GRID/{{ ora_version }}/bin:{{ ansible_env.PATH }}"
  args:
    executable:                        /bin/csh
  register:                            srvctl_check
  failed_when:                         false
  changed_when:                        false

- name:                                "4.1.3 Oracle Data Guard - Primary - Post Processing: Disable automatic restart for database on Primary"
  when :
                                       - srvctl_check.rc == 0
                                       - "'PRCC-1120' not in srvctl_check.stdout"
                                       - "'PRCC-1001' not in srvctl_check.stdout"
  become:                              true
  become_user:                         "{{ oracle_user_name }}"
  ansible.builtin.shell: |
                                       srvctl disable database -d {{ db_sid | upper }}
  environment:
    ORACLE_HOME:                       "/oracle/{{ db_sid | upper }}/{{ ora_version }}"
    PATH:                              "/oracle/GRID/{{ ora_version }}/bin:{{ ansible_env.PATH }}"
  args:
    executable:                        /bin/csh
  register:                            disable_restart_primary
  failed_when:
                                      - disable_restart_primary.rc not in [0, 2]
                                      - "'PRCC-1012' not in disable_restart_primary.stdout"
                                      - "'PRCR-1003' not in disable_restart_primary.stdout"
                                      - "'PRCR-1001' not in disable_restart_primary.stdout"
  changed_when:
                                    - disable_restart_primary.rc == 0

...
