# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---

- name:                                "4.1.3 Oracle Data Guard: Setting the Current host name"
  ansible.builtin.set_fact:
    current_host:                      "{{ ansible_hostname }}"

- name:                                "4.1.3 Oracle Data Guard - Preparation: Create folders"
  become:                              true
  become_user:                         "root"
  ansible.builtin.file:
    path:                              "{{ item.path }}"
    state:                             directory
    owner:                             oracle
    group:                             oinstall
    mode:                              "{{ item.mode }}"
  loop:
    - { mode: '0755', path: '/etc/sap_deployment_automation' }
    - { mode: '0755', path: '/etc/sap_deployment_automation/dataguard_scripts' }
    - { mode: '0755', path: '/oracle/{{ db_sid | upper }}/saptrace' }

- name:                                "4.1.3 Oracle Data Guard - Preparation: Create folders"
  become:                              true
  become_user:                         "root"
  ansible.builtin.file:
    path:                              "{{ item.path }}"
    state:                             directory
    owner:                             oracle
    group:                             oinstall
    mode:                              "{{ item.mode }}"
  loop:
    - { mode: '0755', path: '{{ target_media_location }}/downloads/{{ sap_sid | upper }}' }
    - { mode: '0755', path: '{{ target_media_location }}/downloads/{{ sap_sid | upper }}/dbs' }
  when:
    - ora_primary == ansible_hostname

- name:                                "4.1.3 Oracle Data Guard: - Preparation Create password file"
  when:
                                       - tier != "observer"
  become:                              true
  become_user:                         "{{ oracle_user_name }}"
  ansible.builtin.shell:               "orapwd file=$ORACLE_HOME/dbs/orapw{{ db_sid | upper }} password={{ main_password }} entries=5 format=12"
  environment:
    ORACLE_SID:                        "{{ db_sid | upper }}"
    ORACLE_HOME:                       "/oracle/{{ db_sid | upper }}/{{ ora_version }}"
  args:
    creates:                           /oracle/{{ db_sid | upper }}/{{ ora_version }}/dbs/orapw{{ db_sid | upper }}
    chdir:                             "{{ target_media_location }}/downloads/{{ db_sid | upper }}/dbs"
    executable:                        /bin/csh

- name:                                "4.1.3 Oracle Data Guard: - Validate"
  ansible.builtin.include_tasks:       "00-validate.yaml"

- name:                                "4.1.3 Oracle Data Guard: - Prepare primary node"
  when:
    - ora_primary == ansible_hostname
  ansible.builtin.include_tasks:       "01-prepare-primary.yaml"

- name:                                "4.1.3 Oracle Data Guard: - Prepare secondary node"
  when:
    - ora_secondary == ansible_hostname
  ansible.builtin.include_tasks:       "02-prepare-secondary.yaml"


- name:                                "4.1.3 Oracle Data Guard - Prepare Secondary - Test connectivity primary -> standby"
  become_user:                         "{{ oracle_user_name }}"
  become:                              true
  ansible.builtin.shell:               |
                                       sqlplus -s sys/{{ main_password }}@{{ db_sid | upper }}_STDBY as sysdba <<EOF
                                       SELECT 'connected' FROM dual;
                                       EXIT;
                                       EOF
  register:                            conn_test
  changed_when:                        false
  failed_when:                         "'connected' not in conn_test.stdout"
  args:
    chdir:                             "/oracle/{{ db_sid | upper }}/{{ ora_version }}/bin"
    executable:                        /bin/csh
  when:
    - inventory_hostname == ora_primary

- name:                                "4.1.3 Oracle Data Guard - Prepare Secondary - Test connectivity standby -> primary"
  become_user:                         "{{ oracle_user_name }}"
  become:                              true
  when:                                inventory_hostname == ora_secondary
  ansible.builtin.shell:               |
                                       sqlplus -s sys/{{ main_password }}@{{ db_sid | upper }} as sysdba <<EOF
                                       SELECT 'connected' FROM dual;
                                       EXIT;
                                       EOF
  register:                            conn_test_reverse
  changed_when:                        false
  failed_when:                         "'connected' not in conn_test_reverse.stdout"
  args:
    chdir:                             "/oracle/{{ db_sid | upper }}/{{ ora_version }}/bin"
    executable:                        /bin/csh


- name:                                "4.1.3 Oracle Data Guard: - Duplicate the database"
  when:
    - ora_secondary == ansible_hostname
  ansible.builtin.include_tasks:       "03-duplicate-database.yaml"

- name:                                "4.1.3 Oracle Data Guard: - Finalize"
  ansible.builtin.include_tasks:       "04-finalize.yaml"

- name:                                "4.1.3 Oracle Data Guard: - Fail"
  ansible.builtin.fail:
    msg:                               "After 01-prepare-primary.yaml"


# FSFO is enabled from the Observer.
- name:                                "4.1.3 Oracle Data Guard: - Setup Observer"
  when:
                                       - node_tier == "observer"
                                       - action    == 'Setup_Observer'
  ansible.builtin.include_tasks:       "ora-dg-observer-setup.yaml"

...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
