# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---

# /*---------------------------------------------------------------------------8
# |Execute the SQL scripts  for  data guard initial configuration.             |
# |                                                                            |
# |                                                                            |
# |                                                                            |
# +------------------------------------4--------------------------------------*/


# Set Primary and Secondary node names.
- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Define variables"
  ansible.builtin.set_fact:
    ora_primary:                "{{ ansible_play_hosts_all[0] }}"         # Oracle Primary Host
    ora_secondary:              "{{ ansible_play_hosts_all[1] }}"         # Oracle Secondary Host
    current_host:               "{{ ansible_hostname }}"

# Steps to be run on Primary DB

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Check if archive_enabled_on_primary.txt exists"
  ansible.builtin.stat:
    path:                              /etc/sap_deployment_automation/dataguard_scripts/archive_enabled_on_primary.txt
  register:                            archive_primary_stat
  when:  current_host == ora_primary

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Enable Archive log on Primary"  # In a typical SWPM installation archive log is always enabled.
  become:                              true
  become_user:                         "{{ oracle_user_name }}"
  ansible.builtin.shell:               sqlplus / as sysdba @enable_archive_log.sql
  register:                            enable_archive_log_results
  failed_when:                         enable_archive_log_results.rc >= 2
  args:
    creates:                           /etc/sap_deployment_automation/dataguard_scripts/archive_enabled_on_primary.txt
    chdir:                             /etc/sap_deployment_automation/dataguard_scripts
    executable:                        /bin/csh
  when:
  #  - not archive_primary_stat.stat.exists
    - current_host == ora_primary

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Enable Archive log on Primary (debug)"
  ansible.builtin.debug:
    var:                               enable_archive_log_results.stdout_lines
    verbosity:                         2

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Enable Archive log on Primary (save output)"
  ansible.builtin.copy:
    dest:                              /etc/sap_deployment_automation/dataguard_scripts/enable_archive.log
    content:                           "{{ enable_archive_log_results.stdout }}"
    mode:                              '0777'
  when:                                enable_archive_log_results.stdout is defined

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Create archive_enabled_on_primary.txt"
  become:                              true
  become_user:                         "{{ oracle_user_name }}"
  ansible.builtin.file:
    path:                              /etc/sap_deployment_automation/dataguard_scripts/archive_enabled_on_primary.txt
    state:                             touch
    mode:                              '0755'
  when:
    - current_host == ora_primary
    - enable_archive_log_results.rc < 2

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Check if 'enable_force_login.txt' exists"
  ansible.builtin.stat:
    path:                              /etc/sap_deployment_automation/dataguard_scripts/enable_force_login.txt
  register:                            forcelogin_stat
  when:  current_host == ora_primary

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Enable enable_force_login on Primary"
  become:                              true
  become_user:                         "{{ oracle_user_name }}"
  ansible.builtin.shell: |
                                       sqlplus / as sysdba @enable_forced_logging.sql
  register:                            enable_force_logging_results
  failed_when:                         enable_force_logging_results.rc >= 2
  args:
    creates:                           /etc/sap_deployment_automation/dataguard_scripts/enable_force_login.txt
    chdir:                             /etc/sap_deployment_automation/dataguard_scripts
    executable:                        /bin/csh
  when:
  #  - not forcelogin_stat.stat.exists
    - current_host == ora_primary

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Enable enable_force_login on Primary (debug)"
  ansible.builtin.debug:
    var:                               enable_force_logging_results.stdout_lines
    verbosity:                         2

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Enable enable_force_login on Primary (save output)"
  ansible.builtin.copy:
    dest:                              /etc/sap_deployment_automation/dataguard_scripts/switch_archive.log
    content:                           "{{ enable_force_logging_results.stdout }}"
    mode:                              '0777'
  when:                                enable_force_logging_results.stdout is defined

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Create enable_force_login.txt"
  become:                              true
  become_user:                         "{{ oracle_user_name }}"
  ansible.builtin.file:
    path:                              /etc/sap_deployment_automation/dataguard_scripts/enable_force_login.txt
    state:                             touch
    mode:                              '0755'
  when:
    - current_host == ora_primary
    - enable_archive_log_results.rc < 2

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Create oracle standbylog directory"
  ansible.builtin.file:
    path:                              /oracle/{{ db_sid | upper }}/oraarch/standbylog
    mode:                              '0755'
    state:                             directory
    owner:                             oracle
    group:                             oinstall
  when:  current_host == ora_primary

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Create standby logs for Oracle DG"
  become:                              true
  become_user:                         "{{ oracle_user_name }}"
  ansible.builtin.shell:               sqlplus / as sysdba @standby_redo_logs.sql
  register:                            standby_redo_log_results
  failed_when:                         standby_redo_log_results.rc >= 2
  args:
    creates:                           /etc/sap_deployment_automation/dataguard_scripts/standby_redo_logs.txt
    chdir:                             /etc/sap_deployment_automation/dataguard_scripts
    executable:                        /bin/csh
  when:  current_host == ora_primary

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Create standby logs for Oracle DG (debug)"
  ansible.builtin.debug:
    var:                               standby_redo_log_results.stdout_lines
    verbosity:                         2

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Create standby logs for Oracle DG (save output)"
  ansible.builtin.copy:
    dest:                              /etc/sap_deployment_automation/dataguard_scripts/standby_logs.log
    content:                           "{{ standby_redo_log_results.stdout }}"
    mode:                              '0777'
  when:                                standby_redo_log_results.stdout is defined

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Create standby_redo_logs.txt"
  become:                              true
  become_user:                         "{{ oracle_user_name }}"
  ansible.builtin.file:
    path:                              /etc/sap_deployment_automation/dataguard_scripts/standby_redo_logs.txt
    state:                             touch
    mode:                              '0755'
  when:
    - current_host == ora_primary
    - standby_redo_log_results.rc == 0

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Enable Flashback on Oracle Primary DB"
  become:                              true
  become_user:                         "{{ oracle_user_name }}"
  ansible.builtin.shell:               sqlplus / as sysdba @turn_on_flashback.sql
  register:                            turn_on_flashback_results
  failed_when:                         turn_on_flashback_results.rc > 0
  args:
    creates:                           /etc/sap_deployment_automation/dataguard_scripts/turn_on_flashback.txt
    chdir:                             /etc/sap_deployment_automation/dataguard_scripts
    executable:                        /bin/csh
  when:  current_host == ora_primary

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Enable Flashback on Oracle Primary DB (debug)"
  ansible.builtin.debug:
    var:                               turn_on_flashback_results.stdout_lines
    verbosity:                         2

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Enable Flashback on Oracle Primary DB (save output)"
  ansible.builtin.copy:
    dest:                              /etc/sap_deployment_automation/dataguard_scripts/turn_on_flashback.log
    content:                           "{{ turn_on_flashback_results.stdout }}"
    mode:                              '0777'
  when:                                turn_on_flashback_results.stdout is defined

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Create turn_on_flashback.txt"
  become:                              true
  become_user:                         "{{ oracle_user_name }}"
  ansible.builtin.file:
    path:                              /etc/sap_deployment_automation/dataguard_scripts/turn_on_flashback.txt
    state:                             touch
    mode:                              '0755'
  when:
    - current_host == ora_primary
    - turn_on_flashback_results.rc == 0

# - name:                            "Update the Local_Listener Value in primary"
#   become:                              true
#   become_user:                         "{{ oracle_user_name }}"
#   ansible.builtin.shell:               sqlplus / as sysdba @listener_update.sql
#   register:                            local_listener_on_secondary_results
#   failed_when:                         local_listener_on_secondary_results.rc > 0
#   args:
#    creates:                           /etc/sap_deployment_automation/dataguard_scripts/local_listener_on_secondary.txt
#    chdir:                             /etc/sap_deployment_automation/dataguard_scripts
#    executable:                        /bin/csh
#   when:
#     - current_host == ora_primary

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Create Control File"
  become:                              true
  become_user:                         "{{ oracle_user_name }}"
  ansible.builtin.shell:               sqlplus / as sysdba @create_control_file.sql
  register:                            create_control_file_results
  failed_when:                         create_control_file_results.rc > 0
  args:
    creates:                           /usr/sap/install/downloads/{{ db_sid || upper }}/{{ db_sid || upper }}_stby.ctl
    chdir:                             /etc/sap_deployment_automation/dataguard_scripts
    executable:                        /bin/csh
  when:
    - current_host == ora_primary
    - node_tier == "oracle-asm"

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Show create control files result (debug)"
  ansible.builtin.debug:
    var:                               create_control_file_results.stdout_lines
    verbosity:                         2
  when:
   - create_control_file_results.stdout is defined
   - node_tier == "oracle-asm"

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Save create control files result"
  ansible.builtin.copy:
    dest:                              /etc/sap_deployment_automation/dataguard_scripts/create_control_file_results.log
    content:                           "{{ create_control_file_results.stdout }}"
    mode:                              '0777'
  when:
   - node_tier == "oracle-asm"
   - create_control_file_results.stdout is defined

# Setup DG parameters for Primary Database.

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Setup DG parameters on Primary DB"
  become:                              true
  become_user:                         "{{ oracle_user_name }}"
  ansible.builtin.shell:               sqlplus / as sysdba @db_parameters_for_dataguard.sql
  register:                            db_parameters_for_dataguard_results
  failed_when:                         db_parameters_for_dataguard_results.rc > 0
  args:
    creates:                           /etc/sap_deployment_automation/dataguard_scripts/db_parameters_for_dataguard.txt
    chdir:                             /etc/sap_deployment_automation/dataguard_scripts
    executable:                        /bin/csh
  when:
    - current_host == ora_primary
    - node_tier == "oracle-asm"

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Enable Flashback on Oracle Primary DB (debug)"
  ansible.builtin.debug:
    var:                               db_parameters_for_dataguard_results.stdout_lines
    verbosity:                         2
  when:
   - node_tier == "oracle-asm"

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Enable Flashback on Oracle Primary DB (save output)"
  ansible.builtin.copy:
    dest:                              /etc/sap_deployment_automation/dataguard_scripts/db_parameters_for_dataguard.log
    content:                           "{{ turn_on_flashback_results.stdout }}"
    mode:                              '0777'
  when:
   - node_tier == "oracle-asm"
   - db_parameters_for_dataguard_results.stdout is defined

- name:                                "4.1.3 Oracle Data Guard - Setup Primary: - Create db_parameters_for_dataguard.txt"
  become:                              true
  become_user:                         "{{ oracle_user_name }}"
  ansible.builtin.file:
    path:                              /etc/sap_deployment_automation/dataguard_scripts/db_parameters_for_dataguard.txt
    state:                             touch
    mode:                              '0755'
  when:
    - current_host == ora_primary
    - node_tier == "oracle-asm"
    - db_parameters_for_dataguard_results.rc == 0

...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
