# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
# DGMGRL Config on Primary

# # Set Primary and Secondary node names.
# - name:                        Setting the primary and Secondary DB names
#   ansible.builtin.set_fact:
#     ora_primary:                "{{ ansible_play_hosts_all[0] }}"         # Oracle Primary Host
#     ora_secondary:              "{{ ansible_play_hosts_all[1] }}"         # Oracle Secondary Host
#     current_host:               "{{ ansible_hostname }}"

- name:                                "4.1.3 Oracle Data Guard - Primary - Oracle Data Guard -  Check SAP Restore on secondary is completed"
  when:                                node_tier in ["oracle","oracle-asm"]
  ansible.builtin.stat:
    path:                              /usr/sap/install/downloads/{{ db_sid | upper }}/restore_completed.txt
  register:                            secondary_completed


- name:                                "4.1.3 Oracle Data Guard - Primary - Post Processing: Execute tasks after secondary restore completion"
  when:
                                       - secondary_completed.stat.exists
  block:

    # Restart the LSNRCTL START
    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Restart lsnrctl on Primary"
      become:                          true
      become_user:                     "{{ oracle_user_name }}"
      ansible.builtin.shell:           lsnrctl reload
      register:                        lsnrctl_start_primary_results
      failed_when:                     lsnrctl_start_primary_results.rc > 0
      args:
        creates:                       /etc/sap_deployment_automation/dataguard_scripts/lsnrctl_started_primary.txt
        chdir:                         /etc/sap_deployment_automation/dataguard_scripts
        executable:                    /bin/csh
      # when:                                current_host == ora_primary

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Restart lsnrctl on Primary (Debug)"
      ansible.builtin.debug:
        var:                           lsnrctl_start_primary_results.stdout_lines
        verbosity:                     2

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Restart lsnrctl on Primary (save output)"
      when:                            lsnrctl_start_primary_results.stdout is defined
      ansible.builtin.copy:
        dest:                          /etc/sap_deployment_automation/lsnrctl_start_primary.log
        content:                       "{{ lsnrctl_start_primary_results.stdout }}"
        mode:                          '0777'


    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Create lsnrctl_started_sec.txt"
      become:                          true
      become_user:                     "{{ oracle_user_name }}"
      when:                            lsnrctl_start_primary_results.rc == 0
      ansible.builtin.file:
        path:                          /etc/sap_deployment_automation/dataguard_scripts/lsnrctl_started_primary.txt
        state:                         touch
        mode:                          '0755'

      # when:                                current_host == ora_primary

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Enable DG Broker on Primary"
      become:                          true
      become_user:                     "{{ oracle_user_name }}"
      ansible.builtin.shell:           sqlplus / as sysdba @enable_dataguard_broker.sql
      register:                        dg_broker_primary_results
      failed_when:                     dg_broker_primary_results.rc > 0
      args:
        creates:                       /etc/sap_deployment_automation/dataguard_scripts/enable_dg_broker.txt
        chdir:                         /etc/sap_deployment_automation/dataguard_scripts
        executable:                    /bin/csh
      # when:                                current_host == ora_primary

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing:  - Pause 30 secs"
      ansible.builtin.pause:
        seconds:                       30

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Enable DG Broker on Primary"
      ansible.builtin.debug:
        var:                           dg_broker_primary_results.stdout_lines
        verbosity:                     2

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Enable DG Broker on Primary (save output)"
      when:                            dg_broker_primary_results.stdout is defined
      ansible.builtin.copy:
        dest:                          /etc/sap_deployment_automation/dataguard_scripts/dg_broker_primary.log
        content:                       "{{ dg_broker_primary_results.stdout }}"
        mode:                          '0777'

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Create enable_dg_broker.txt"
      become:                          true
      become_user:                     "{{ oracle_user_name }}"
      when:                            dg_broker_primary_results.rc == 0
      ansible.builtin.file:
        path:                          /etc/sap_deployment_automation/dataguard_scripts/enable_dg_broker.txt
        state:                         touch
        mode:                          '0755'

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Create dgmgrl configuration on Primary"
      become:                          true
      become_user:                     "{{ oracle_user_name }}"
      ansible.builtin.shell:           dgmgrl / as sysdba @dataguard_config.dgmgrl
      register:                        dataguard_config_results
      failed_when:                     dataguard_config_results.rc > 0
      args:
        creates:                       /etc/sap_deployment_automation/dataguard_scripts/dg_config.txt
        chdir:                         /etc/sap_deployment_automation/dataguard_scripts
        executable:                    /bin/csh

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Create dgmgrl configuration on Primary (debug)"
      ansible.builtin.debug:
        var:                           dataguard_config_results.stdout_lines
        verbosity:                     2

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Create dgmgrl configuration on Primary (save output)"
      when:                            dataguard_config_results.stdout is defined
      ansible.builtin.copy:
        dest:                          /etc/sap_deployment_automation/dataguard_scripts/dg_create.log
        content:                       "{{ dataguard_config_results.stdout }}"
        mode:                          '0777'


    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Create dg_config.txt"
      become:                          true
      become_user:                     "{{ oracle_user_name }}"
      when:                            dataguard_config_results.rc == 0
      ansible.builtin.file:
        path:                          /etc/sap_deployment_automation/dataguard_scripts/dg_config.txt
        state:                         touch
        mode:                          '0755'

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Enable dgmgrl configuration"
      become:                          true
      become_user:                     "{{ oracle_user_name }}"
      ansible.builtin.shell:           dgmgrl / as sysdba "ENABLE CONFIGURATION"
      register:                        enable_dataguard_config_results
      failed_when:                     enable_dataguard_config_results.rc > 0
      args:
        creates:                       /etc/sap_deployment_automation/dataguard_scripts/dg_enable.txt
        chdir:                         /etc/sap_deployment_automation/dataguard_scripts
        executable:                    /bin/csh

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Show dgmgrl results (debug)"
      ansible.builtin.debug:
        var:                           enable_dataguard_config_results.stdout_lines
        verbosity:                     2

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Save dgmgrl results"
      when:                            enable_dataguard_config_results.stdout is defined
      ansible.builtin.copy:
        dest:                          /etc/sap_deployment_automation/dataguard_scripts/dg_enable.log
        content:                       "{{ enable_dataguard_config_results.stdout }}"
        mode:                          '0777'

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Create dg_enable.txt"
      become:                          true
      become_user:                     "{{ oracle_user_name }}"
      when:                            enable_dataguard_config_results.rc == 0
      ansible.builtin.file:
        path:                          /etc/sap_deployment_automation/dataguard_scripts/dg_enable.txt
        state:                         touch
        mode:                          '0755'


    # Enable the DB trigger for SAP HA
    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Enable DB Trigger"
      become:                          true
      become_user:                     "{{ oracle_user_name }}"
      ansible.builtin.shell:           sqlplus / as sysdba @db_trigger.sql
      register:                        enable_dbtrigger_results
      failed_when:                     enable_dbtrigger_results.rc > 0
      args:
        creates:                       /etc/sap_deployment_automation/dataguard_scripts/enable_dbtrigger.txt
        chdir:                         /etc/sap_deployment_automation/dataguard_scripts
        executable:                    /bin/csh

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Show dbtrigger results"
      ansible.builtin.debug:
        var:                           enable_dbtrigger_results.stdout_lines
        verbosity:                     2

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Save dbtrigger results"
      when:                            enable_dbtrigger_results.stdout is defined
      ansible.builtin.copy:
        dest:                          /etc/sap_deployment_automation/dataguard_scripts/enable_dbtrigger.log
        content:                       "{{ enable_dbtrigger_results.stdout }}"
        mode:                          '0777'


    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Create enable_dbtrigger.txt"
      become:                          true
      become_user:                     "{{ oracle_user_name }}"
      when:                            enable_dbtrigger_results.rc == 0
      ansible.builtin.file:
        path:                          /etc/sap_deployment_automation/dataguard_scripts/enable_dbtrigger.txt
        state:                         touch
        mode:                          '0755'


    # Enable the DB trigger for SAP HA
    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Enable DB Trigger"
      become:                          true
      become_user:                     "{{ oracle_user_name }}"
      ansible.builtin.shell:           sqlplus / as sysdba @db_trigger.sql
      register:                        enable_dbtrigger_results
      failed_when:                     enable_dbtrigger_results.rc > 0
      args:
        creates:                       /etc/sap_deployment_automation/dataguard_scripts/enable_dbtrigger.txt
        chdir:                         /etc/sap_deployment_automation/dataguard_scripts
        executable:                    /bin/csh

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Show dbtrigger results (debug)"
      ansible.builtin.debug:
        var:                           enable_dbtrigger_results.stdout_lines
        verbosity:                     2

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Save dbtrigger results"
      when:                            enable_dbtrigger_results.stdout is defined
      ansible.builtin.copy:
        dest:                          /etc/sap_deployment_automation/dataguard_scripts/enable_dbtrigger.log
        content:                       "{{ enable_dbtrigger_results.stdout }}"
        mode:                          '0777'

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Create enable_dbtrigger.txt"
      become:                          true
      become_user:                     "{{ oracle_user_name }}"
      when:                            enable_dbtrigger_results.rc == 0
      ansible.builtin.file:
        path:                          /etc/sap_deployment_automation/dataguard_scripts/enable_dbtrigger.txt
        state:                         touch
        mode:                          '0755'

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Disable automatic restart for database on Primary"
      become:                          true
      become_user:                     "{{ oracle_user_name }}"
      ansible.builtin.shell: |
                                       srvctl disable database -d {{ db_sid | upper }}
      environment:
        ORACLE_HOME:                   "/oracle/{{ db_sid | upper }}/{{ ora_version }}"
        PATH:                          "/oracle/GRID/{{ ora_version }}/bin:{{ ansible_env.PATH }}"
      args:
        executable:                    /bin/csh
      register:                        disable_restart_primary
      failed_when:
                                       - disable_restart_primary.rc not in [0, 2]
                                       - "'PRCC-1012' not in disable_restart_primary.stdout"
                                       - "'PRCR-1003' not in disable_restart_primary.stdout"
      changed_when:
                                       - disable_restart_primary.rc == 0

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Verify database is open on Primary"
      become:                          true
      become_user:                     "{{ oracle_user_name }}"
      ansible.builtin.shell: |
                                       sqlplus -s / as sysdba << EOF
                                       SET HEADING OFF
                                       SET FEEDBACK OFF
                                       SELECT open_mode FROM v\$database;
                                       EXIT;
                                       EOF
      environment:
        ORACLE_SID:                    "{{ db_sid | upper }}"
        ORACLE_HOME:                   "/oracle/{{ db_sid | upper }}/{{ ora_version }}"
      args:
        executable:                    /bin/csh
      register:                        primary_open_mode
      failed_when:                     "'READ WRITE' not in primary_open_mode.stdout"
      changed_when:                    false

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Ensure database is open on Primary"
      become:                          true
      become_user:                     "{{ oracle_user_name }}"
      ansible.builtin.shell: |
                                       sqlplus -s / as sysdba << EOF
                                       ALTER DATABASE OPEN;
                                       EXIT;
                                       EOF
      environment:
        ORACLE_SID:                    "{{ db_sid | upper }}"
        ORACLE_HOME:                   "/oracle/{{ db_sid | upper }}/{{ ora_version }}"
      args:
        executable:                    /bin/csh
      when:                            "'READ WRITE' not in primary_open_mode.stdout"
      register:                        open_primary
      failed_when:                     open_primary.rc != 0 and 'ORA-01531' not in open_primary.stderr

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Create disable_restart_primary.txt"
      ansible.builtin.file:
        path:                          /etc/sap_deployment_automation/dataguard_scripts/disable_restart_primary.txt
        state:                         touch
        mode:                          '0755'

    - name:                            "4.1.3 Oracle Data Guard - Primary - Post Processing: Create post processing completed"
      become:                          true
      become_user:                     root
      ansible.builtin.file:
        path:                          /usr/sap/install/downloads/{{ db_sid | upper }}/post_processing_completed.txt
        state:                         touch
        mode:                          '0755'
        owner:                         "{{ oracle_user_name }}"
        group:                         oinstall

...
  # /*---------------------------------------------------------------------------8
  # |                                   END                                      |
  # +------------------------------------4--------------------------------------*/
