# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# -------------------------------------+---------------------------------------8
#                                                                              |
# Defines the parameters and variables for the Control Plane                   |
#                                                                              |
# -------------------------------------+---------------------------------------8

parameters:

  - name:                              control_plane_name
    displayName:                       "Environment name, MGMT, DEV, QA, etc"
    type:                              string
    default:                           CTL-SECE-DEP02

  - name:                              use_deployer
    displayName:                       Run on self hosted agent
    type:                              boolean
    default:                           false

  - name:                              connection_name
    displayName:                       Service Connection Name
    type:                              string
    default:                           Control_Plane_Service_Connection

  - name:                              force_reset
    displayName:                       Force a re-install - may require multiple re-runs
    type:                              boolean
    default:                           false

variables:
  - group:                             "SDAF-General"

  - group:                             SDAF-${{ parameters.control_plane_name }}

  - name:                              run_on
    value:                             $[replace(replace('True',eq(${{ parameters.use_deployer }}, 'True'), variables['POOL']),'True',variables['Agent'])]

  - name:                              variable_group
    value:                             SDAF-${{ parameters.control_plane_name }}

  - name:                              log
    value:                             logfile_$(Build.BuildId)

  - name:                              tf_url
    value:                             https://releases.hashicorp.com/terraform/$(tf_version)/terraform_$(tf_version)_linux_amd64.zip

  - name:                              this_agent
    value:                             $[upper(coalesce(variables['POOL'], variables['Agent']))]

  - name:                              connection_name
    value:                             ${{ parameters.connection_name }}

  - name:                              control_plane_name
    value:                             ${{ parameters.control_plane_name }}

  - name:                              force_reset
    value:                             ${{ parameters.force_reset }}

  - name:                              library_foldername
    value:                             $[format('{0}-{1}-SAP_LIBRARY', split('${{ parameters.control_plane_name }}', '-')[0], split('${{ parameters.control_plane_name }}', '-')[1])]

  - name:                              library_tfvars_filename
    value:                             $[format('{0}-{1}-SAP_LIBRARY.tfvars', split('${{ parameters.control_plane_name }}', '-')[0], split('${{ parameters.control_plane_name }}', '-')[1])]

  - name:                              deployer_foldername
    value:                             $[format('{0}-INFRASTRUCTURE', '${{ parameters.control_plane_name }}')]

  - name:                              deployer_tfvars_filename
    value:                             $[format('{0}-INFRASTRUCTURE.tfvars', '${{ parameters.control_plane_name }}')]

