# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#--------------------------------------+---------------------------------------8
#                                                                              |
# Defines the parameters and variables for the Control Plane                   |
#                                                                              |
#--------------------------------------+---------------------------------------8

parameters:
  - name:                              control_plane_name
    displayName:                       "Control Plane configuration name, use the following syntax: ENV-LOCA-VNET"
    type:                              string
    default:                           MGMT-WEEU-DEP00

  - name:                              use_deployer
    displayName:                       Run on self hosted agent
    type:                              boolean
    default:                           false

  - name:                              connection_name
    displayName:                       Service Connection Name
    type:                              string
    default:                           Control_Plane_Service_Connection

  - name:                              force_reset
    displayName:                       Force a re-install - may require multiple re-runs
    type:                              boolean
    default:                           false

variables:
  - group:                             "SDAF-General"

  - group:                             SDAF-${{ parameters.environment }}

  - name:                              run_on
    value:                             $[replace(replace('True',eq(${{ parameters.use_deployer }}, 'True'), variables['POOL']),'True',variables['AGENT'])]

  - name:                              variable_group
    value:                             SDAF-${{ parameters.environment }}

  - name:                              use_webapp
    value:                             ${{ lower(parameters.use_webapp_param) }}

  - name:                              deployer_foldername
    value:                             ${{ parameters.deployer }}

  - name:                              deployer_tfvars_filename
    value:                             ${{ parameters.deployer }}.tfvars

  - name:                              library_foldername
    value:                             ${{ parameters.library }}

  - name:                              library_tfvars_filename
    value:                             ${{ parameters.library }}.tfvars

  - name:                              log
    value:                             logfile_$(Build.BuildId)

  - name:                              tf_url
    value:                             https://releases.hashicorp.com/terraform/$(tf_version)/terraform_$(tf_version)_linux_amd64.zip

  - name:                              this_agent
    value:                             $[upper(coalesce(variables['POOL'], variables['AGENT']))]

  - name:                              connection_name
    value:                             ${{ parameters.connection_name }}

  - name:                              force_reset
    value:                             ${{ parameters.force_reset }}

  - name:                              control_plane_name
    value:                             $[upper(format('{0}-{1}-{2}', split('${{ parameters.deployer }}', '-')[0], split('${{ parameters.deployer }}', '-')[1], split('${{ parameters.deployer }}', '-')[2]))]
