# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# --------------------------------------+---------------------------------------8
#                                                                               |
# Defines the parameters and variables for the SAP Workload Zone                |
#                                                                               |
# --------------------------------------+---------------------------------------8

parameters:
  - name:                              workload_zone
    displayName:                       "Workload zone configuration name, use the following syntax: ENV-LOCA-VNET-INFRASTRUCTURE"
    type:                              string
    default:                           DEV-WEEU-SAP01-INFRASTRUCTURE

  - name:                              workload_zone_name
    displayName:                       Workload Zone Name
    type:                              string
    default:                           DEV-WEEU-SAP01

  - name:                              control_plane_name
    displayName:                       Control Plane Name
    type:                              string
    default:                           MGMT-WEEU-DEP01

  - name:                              inherit_settings
    displayName:                       Inherit Terraform state file information from control plane
    type:                              boolean
    default:                           true

  - name:                              test
    displayName:                       Test only
    type:                              boolean
    default:                           false

variables:
  - group:                             "SDAF-General"

  - group:                             SDAF-${{ parameters.control_plane_name }}

  - group:                             SDAF-${{ parameters.workload_zone_name }}

  - name:                              parent_variable_group
    value:                             SDAF-${{ parameters.control_plane_name }}

  - name:                              variable_group
    value:                             SDAF-${{ parameters.workload_zone_name }}

  - name:                              workload_zone_foldername
    value:                             ${{ parameters.workload_zone }}

  - name:                              workload_zone_tfvars_filename
    value:                             ${{ parameters.workload_zone }}.tfvars

  - name:                              inherit
    value:                             $[lower(${{ parameters.inherit_settings }})]

  - name:                              tf_url
    value:                             https://releases.hashicorp.com/terraform/$(tf_version)/terraform_$(tf_version)_linux_amd64.zip

  - name:                              this_agent
    value:                             $[lower(coalesce(variables['POOL'], variables['Agent']))]

  - name:                              test
    value:                             ${{ parameters.test }}
