# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# -------------------------------------+---------------------------------------8
#                                                                              |
# Defines the parameters and variables for the SAP System                      |
#                                                                              |
# -------------------------------------+---------------------------------------8

parameters:
  sap_system: ''
  environment: ''
  test: false

variables:
  - group:                             "SDAF-General"

  - group:                             SDAF-$$[format('{0}-{1}-{2}', split('${{ parameters.sap_system }}', '-')[0], split('${{ parameters.sap_system }}', '-')[1],, split('${{ parameters.sap_system }}', '-')[2])]

  - name:                              sap_system_foldername
    value:                             ${{ parameters.sap_system }}

  - name:                              sap_system_tfvars_filename
    value:                             ${{ parameters.sap_system }}.tfvars

  - name:                              tf_url
    value:                             https://releases.hashicorp.com/terraform/$(tf_version)/terraform_$(tf_version)_linux_amd64.zip

  - name:                              variable_group
    value:                             SDAF-$$[format('{0}-{1}-{2}', split('${{ parameters.sap_system }}', '-')[0], split('${{ parameters.sap_system }}', '-')[1],, split('${{ parameters.sap_system }}', '-')[2])]

  - name:                              this_agent
    value:                             $[lower(coalesce(variables['POOL'], variables['Agent']))]

  - name:                              test_only
    value:                             ${{ parameters.test }}
