# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#--------------------------------------+---------------------------------------8
#                                                                              |
# Defines the parameters and variables for the SAP System                      |
#                                                                              |
#--------------------------------------+---------------------------------------8

parameters:
  - name:                              workload_zone_name
    displayName:                       "Workload zone configuration name, use the following syntax: ENV-LOCA-VNET"
    type:                              string

  - name:                              sap_system
    displayName:                       "SAP System name, use the following syntax: ENV-LOCA-VNET-SID"
    type:                              string

  - name:                              environment
    displayName:                       "SAP System environment"
    type:                              string

  - name:                              test
    displayName:                       "SAP System test only"
    type:                              string
    default:                           false

variables:
  - group:                             "SDAF-General"

  - group:                             SDAF-${{ parameters.workload_zone_name }}

  - name:                              sap_system_foldername
    value:                             ${{ parameters.sap_system }}

  - name:                              sap_system_tfvars_filename
    value:                             ${{ parameters.sap_system }}.tfvars

  - name:                              tf_url
    value:                             https://releases.hashicorp.com/terraform/$(tf_version)/terraform_$(tf_version)_linux_amd64.zip

  - name:                              variable_group
    value:                             SDAF-${{ parameters.environment }}

  - name:                              this_agent
    value:                             $[lower(coalesce(variables['POOL'], variables['AGENT']))]

  - name:                              REMOTE_STATE_SA
    value:                             $[variables['TERRAFORM_REMOTE_STORAGE_ACCOUNT_NAME']]

  - name:                              STATE_SUBSCRIPTION
    value:                             $[variables['ARM_SUBSCRIPTION_ID']]

  - name:                              deployer_tfstate_key
    value:                             $[variables['DEPLOYER_STATE_FILENAME']]

  - name:                              key_vault
    value:                             $[variables['DEPLOYER_KEYVAULT']]

  - name:                              test_only
    value:                             ${{ parameters.test }}

  - name:                              workload_zone_name
    value:                             $[upper(${{ parameters.workload_zone_name }})]
