---
# /*---------------------------------------------------------------------------8
# |                                                                            |
# |               This pipeline deploys the control plane                      |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

parameters:

  - name:                              control_plane_name
    displayName:                       "Control Plane Name, use the following syntax: ENV-LOCA-VNET"
    type:                              string
    default:                           MGMT-WEEU-DEP01

  - name:                              use_deployer
    displayName:                       Run on self hosted agent
    type:                              boolean
    default:                           false

  - name:                              sap_automation_repo_path
    displayName:                       The local path on the agent where the sap_automation repo can be found
    type:                              string

  - name:                              config_repo_path
    displayName:                       The local path on the agent where the config repo can be found
    type:                              string

  - name:                              connection_name
    displayName:                       Service Connection Name
    type:                              string

  - name:                              force_reset
    displayName:                       Force a re-install - may require multiple re-runs
    type:                              boolean

stages:
  - stage:                             Prepare_Deployer
    condition:                         and(not(failed()), not(canceled()))
    variables:
      - template:                      variables/01-deploy-control-plane-variables.yaml
        parameters:
          control_plane_name:          ${{ parameters.control_plane_name }}
          use_deployer:                ${{ parameters.use_deployer }}
          force_reset:                 ${{ parameters.force_reset }}
    displayName:                       Prepare the self hosted agent(s)

    jobs:
      - job:                           Prepare_Deployer
        displayName:                   Prepare the self hosted agent
        workspace:
          clean:                       all
        steps:
          - template:                  templates\download.yaml
          - task:                      PostBuildCleanup@4
          # Set Variables.
          - task:                      AzureCLI@2
            continueOnError:           false
            inputs:
              azureSubscription:       ${{parameters.connection_name}}
              scriptType:              bash
              scriptLocation:          'scriptPath'
              scriptPath:              $(System.DefaultWorkingDirectory)/sap-automation/deploy/scripts/pipeline_scripts/01-control-plane-prepare.sh
              addSpnToEnvironment:     true
              visibleAzLogin:          false
              failOnStandardError:     false

            displayName: Prepare control plane
            env:
              AZURE_DEVOPS_EXT_PAT:           $(PAT)
              CONFIG_REPO_PATH:               ${{ parameters.config_repo_path }}/$(Deployment_Configuration_Path)
              CONTROL_PLANE_NAME:             ${{ parameters.control_plane_name }}
              DEPLOYER_TFSTATE_KEY:           "${{ parameters.control_plane_name }}-INFRASTRUCTURE.terraform.tfstate"
              FORCE_RESET:                    ${{ lower(parameters.force_reset) }}
              IS_PIPELINE_DEPLOYMENT:         true
              POOL:                           $(POOL)
              SAP_AUTOMATION_REPO_PATH:       ${{ parameters.sap_automation_repo_path }}
              SYSTEM_ACCESSTOKEN:             $(System.AccessToken)
              TF_IN_AUTOMATION:               true
              TF_LOG:                         $(TF_LOG)
              TF_VAR_agent_ado_url:           $(System.CollectionUri)
              TF_VAR_agent_pat:               $(PAT)
              TF_VAR_agent_pool:              $(POOL)
              TF_VAR_ansible_core_version:    $(ansible_core_version)
              TF_VAR_tf_version:              $(tf_version)
              TF_VAR_app_registration_app_id: $(APP_REGISTRATION_APP_ID)
              USE_MSI:                        $(Use_MSI)
  - stage:                             DeployControlplaneStage
    dependsOn:
                                       - Prepare_Deployer
    condition:                         eq(dependencies.Prepare_Deployer.result, 'Succeeded')
    pool:                              $(this_agent)
    variables:
      - template:                      variables/01-deploy-control-plane-variables.yaml
        parameters:
          control_plane_name:          ${{ parameters.control_plane_name }}
          use_deployer:                ${{ parameters.use_deployer }}
          force_reset:                 ${{ parameters.force_reset }}
    displayName:                       Deploy the control plane

    jobs:
      - job:                           DeployControlplaneJob
        displayName:                   Deploy the control plane
        workspace:
          clean:                       all
        steps:
          - task:                      PostBuildCleanup@4
          - template:                  templates\download.yaml
            parameters:
              getLatestFromBranch: true

          - task:                      Bash@3
            name:                      ParameterValidation
            displayName:               Parameter Validation
            inputs:
              targetType:              'filePath'
              filePath:                "$(System.DefaultWorkingDirectory)/sap-automation/deploy/scripts/pipeline_scripts/00-validate-credentials.sh"
              failOnStderr:            false
              workingDirectory:        "$(System.DefaultWorkingDirectory)"
            env:
              AZURE_DEVOPS_EXT_PAT:    $(System.AccessToken)
              SYSTEM_COLLECTIONURI:    $(System.CollectionUri)
              SYSTEM_TEAMPROJECT:      $(System.TeamProject)

          - task: Bash@3
            inputs:
              targetType:              'filePath'
              filePath:                "$(System.DefaultWorkingDirectory)/sap-automation/deploy/scripts/pipeline_scripts/01-control-plane-deploy.sh"
              failOnStderr:            false
              workingDirectory:        "$(System.DefaultWorkingDirectory)"
            displayName:               Deploy control plane Part 2
            env:
              APPLICATION_CONFIGURATION_ID:   $(APPLICATION_CONFIGURATION_ID)
              APP_REGISTRATION_APP_ID:        $(APP_REGISTRATION_APP_ID)
              ARM_CLIENT_ID:                  $(ParameterValidation.ARM_CLIENT_ID)
              ARM_CLIENT_SECRET:              $(ParameterValidation.ARM_CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID:            $(ParameterValidation.ARM_SUBSCRIPTION_ID)
              ARM_TENANT_ID:                  $(ParameterValidation.ARM_TENANT_ID)
              AZURE_DEVOPS_EXT_PAT:           $(System.AccessToken)
              CONFIG_REPO_PATH:               ${{ parameters.config_repo_path }}/$(Deployment_Configuration_Path)
              CONTROL_PLANE_NAME:             ${{ parameters.control_plane_name }}
              DEPLOYER_TFSTATE_KEY:           "${{ parameters.control_plane_name }}-INFRASTRUCTURE.terraform.tfstate"
              FORCE_RESET:                    ${{ lower(parameters.force_reset) }}
              IS_PIPELINE_DEPLOYMENT:         true
              POOL:                           $(POOL)
              SAP_AUTOMATION_REPO_PATH:       ${{ parameters.sap_automation_repo_path }}
              SYSTEM_ACCESSTOKEN:             $(System.AccessToken)
              TF_IN_AUTOMATION:               true
              TF_LOG:                         $(TF_LOG)
              TF_VAR_agent_ado_url:           $(System.CollectionUri)
              TF_VAR_agent_pat:               $(PAT)
              TF_VAR_agent_pool:              $(POOL)
              TF_VAR_ansible_core_version:    $(ansible_core_version)
              TF_VAR_spn_id:                  $(ParameterValidation.ARM_OBJECT_ID)
              TF_VAR_app_registration_app_id: $(APP_REGISTRATION_APP_ID)
              TF_VAR_tf_version:              $(tf_version)
              USE_MSI:                        $(Use_MSI)
          - task: Bash@3
            inputs:
              targetType:              'filePath'
              filePath:                "$(System.DefaultWorkingDirectory)/sap-automation/deploy/scripts/pipeline_scripts/01-webapp-variables.sh"
              failOnStderr:            false
            displayName:               "Get Web App Variables"
            name:                      GetWebAppVariables
            env:
              APPLICATION_CONFIGURATION_ID: $(APPLICATION_CONFIGURATION_ID)
              CONTROL_PLANE_NAME:           ${{ parameters.control_plane_name }}

  - stage:                             Web_App_Deployment
    pool:                              $(this_agent)
    variables:
      - template:                      variables/01-app-service-variables.yaml
        parameters:
          control_plane_name:          ${{ parameters.control_plane_name }}
          use_deployer:                ${{ parameters.use_deployer }}
    displayName:                       Deploy SAP configuration Web App
    dependsOn:
      - Prepare_Deployer
      - DeployControlplaneStage
    condition: |
      and
      (
        eq(dependencies.DeployControlplaneStage.result, 'Succeeded'),
        eq(dependencies.Prepare_Deployer.result, 'Succeeded')

      )
    jobs:
      - job:                           Deploy_web_app
        variables:
          APPSERVICE_NAME:             $[ stageDependencies.DeployControlplaneStage.DeployControlplaneJob.outputs['GetWebAppVariables.APPSERVICE_NAME']]
        displayName:                   Deploy SAP configuration Web App
        workspace:
          clean:                       all
        steps:
          - template:                  templates\download.yaml
          - task:                      PostBuildCleanup@4
          - task:                      DotNetCoreCLI@2
            displayName:               "Build the Configuration Web Application"
            inputs:
              command:                 "build"
              projects:                "$(System.DefaultWorkingDirectory)/sap-automation/Webapp/SDAF/*.csproj"
          - task:                      DotNetCoreCLI@2
            displayName:               "Publish the Configuration Web Application"
            inputs:
              command:                 publish
              projects:                "**/Webapp/**/*.csproj"
              publishWebProjects:      false
              arguments:               "--output $(Build.ArtifactStagingDirectory)/WebApp"
              zipAfterPublish:         true
              modifyOutputPath:        true

          - task:                      AzureWebApp@1
            displayName:               "Deploy the Configuration Web Application"
            inputs:
              azureSubscription:       ${{parameters.connection_name}}
              appType:                 "webApp"
              appName:                 $(APPSERVICE_NAME)
              package:                 "$(Build.ArtifactStagingDirectory)/WebApp/*.zip"
              deploymentMethod:        "auto"
              appSettings: '-CollectionUri $(System.CollectionUri)
                            -ProjectName "$(System.TeamProject)"
                            -RepositoryId $(Build.Repository.ID)
                            -SourceBranch "$(Build.SourceBranchName)"
                            -WORKLOADZONE_PIPELINE_ID $(WORKLOADZONE_PIPELINE_ID)
                            -SYSTEM_PIPELINE_ID $(SYSTEM_PIPELINE_ID)
                            -SAP_INSTALL_PIPELINE_ID $(SAP_INSTALL_PIPELINE_ID)
                            -SDAF_GENERAL_GROUP_ID $(SDAF_GENERAL_GROUP_ID)
                            -IS_PIPELINE_DEPLOYMENT true
                            -CONTROLPLANE_NAME $CONTROLPLANE_NAME'
            env:
              ARM_SUBSCRIPTION_ID:       $(ParameterValidation.ARM_SUBSCRIPTION_ID)
              SYSTEM_PIPELINE_ID:        $(SYSTEM_PIPELINE_ID)
              WORKLOADZONE_PIPELINE_ID:  $(WORKLOADZONE_PIPELINE_ID)
              SAP_INSTALL_PIPELINE_ID:   $(SAP_INSTALL_PIPELINE_ID)
              SDAF_GENERAL_GROUP_ID:     $(SDAF_GENERAL_GROUP_ID)
              APPSERVICE_NAME:           $(APPSERVICE_NAME)
              APP_TENANT_ID:             $(ParameterValidation.ARM_TENANT_ID)
              AZURE_CONNECTION_NAME:     ${{variables.connection_name}}
              CONTROLPLANE_NAME:         ${{ parameters.control_plane_name }}

          - task: Bash@3
            inputs:
              targetType:              'filePath'
              filePath:                "$(System.DefaultWorkingDirectory)/sap-automation/deploy/scripts/pipeline_scripts/01-webapp-configuration.sh"
              failOnStderr:            false
            displayName:               "Document the Web App configuration steps"
            name:                      Document
            env:
              APPLICATION_CONFIGURATION_ID: $(APPLICATION_CONFIGURATION_ID)
              CONTROL_PLANE_NAME:           ${{ parameters.control_plane_name }}
              APP_REGISTRATION_APP_ID:      $(APP_REGISTRATION_APP_ID)
              APP_REGISTRATION_OBJECT_ID:   $(APP_REGISTRATION_OBJECT_ID)
