# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
# /*---------------------------------------------------------------------------8
# |                                                                            |
# |               This pipeline deploys the Workload Zone                      |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

parameters:
  - name:                              workload_zone_name
    displayName:                       "Workload zone configuration name, use the following syntax: ENV-LOCA-VNET"
    type:                              string
    default:                           DEV-WEEU-SAP01

  - name:                              control_plane_name
    displayName:                       Deployer Environment name (MGMT, DEV, QA, PRD, ...)
    type:                              string
    default:                           MGMT

  - name:                              inherit_settings
    displayName:                       Inherit Terraform state file information from control plane
    type:                              boolean
    default:                           true

  - name:                              sap_automation_repo_path
    displayName:                       The local path on the agent where the sap_automation repo can be found
    type:                              string

  - name:                              config_repo_path
    displayName:                       The local path on the agent where the config repo can be found
    type:                              string

  - name:                              test
    type:                              boolean
    default:                           false

stages:
  - stage:                             PopulateKeyVault
    pool:                              $(this_agent)
    displayName:                       Save the Deployment Credentials in Azure Keyvault
    variables:
      - template:                      variables/02-sap-workload-zone-variables.yaml
        parameters:
          workload_zone_name:          ${{ parameters.workload_zone_name }}
          control_plane_name:          ${{ parameters.control_plane_name   }}
          inherit_settings:            ${{ parameters.inherit_settings }}
    jobs:
      - job:                           SaveDeploymentCredentials
        displayName:                   Save the Deployment Credentials
        workspace:
          clean:                       all
        steps:
          - task:                      PostBuildCleanup@4
          - task:                      TerraformInstaller@1
            displayName:               Install Terraform
            inputs:
              terraformVersion:        latest
          - template:                  templates\download.yaml
            parameters:
              getLatestFromBranch: true
          - task:                      Bash@3
            inputs:
              targetType:              'filePath'
              filePath:                "$(System.DefaultWorkingDirectory)/sap-automation/deploy/scripts/pipeline_scripts/00-store-secrets-in-keyvault.sh"
              failOnStderr:            false
              workingDirectory:        "$(System.DefaultWorkingDirectory)"
            name:                      StoreSecrets_v2
            displayName:               Store deployment credentials in Key Vault (v2)
            env:
              ARM_CLIENT_ID:                $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET:            $(ARM_CLIENT_SECRET)
              ARM_OBJECT_ID:                $(ARM_OBJECT_ID)
              ARM_SUBSCRIPTION_ID:          $(ARM_SUBSCRIPTION_ID)
              ARM_TENANT_ID:                $(ARM_TENANT_ID)
              AZURE_DEVOPS_EXT_PAT:         $(System.AccessToken)
              CONFIG_REPO_PATH:             ${{ parameters.config_repo_path }}/$(Deployment_Configuration_Path)
              SAP_AUTOMATION_REPO_PATH:     ${{ parameters.sap_automation_repo_path }}
              SYSTEM_ACCESSTOKEN:           $(System.AccessToken)
              USE_MSI:                      $(Use_MSI)
              ZONE:                         ${{ upper(parameters.workload_zone_name) }}


  - stage:                             Deploy_SAP_workload_zone
    dependsOn:
                                       - PopulateKeyVault
    condition:                         eq(dependencies.PopulateKeyVault.result, 'Succeeded')
    displayName: Deploy SAP workload zone
    variables:
      - template:                      variables/02-sap-workload-zone-variables.yaml
        parameters:
          workload_zone_name:          ${{ parameters.workload_zone_name }}
          control_plane_name:          ${{ parameters.control_plane_name }}
          inherit_settings:            ${{ parameters.inherit_settings }}
    jobs:
      - job:                           Deploy_SAP_workload_zone
        displayName:                   Deploy SAP workload zone
        workspace:
          clean:                       all
        steps:
          - template:                  templates\download.yaml
          - task:                      PostBuildCleanup@4
          - task:                      TerraformInstaller@1
            displayName:               Install Terraform
            inputs:
              terraformVersion:        latest
          - task:                      Bash@3
            inputs:
              targetType:              'filePath'
              filePath:                "$(System.DefaultWorkingDirectory)/sap-automation/deploy/scripts/pipeline_scripts/02-sap-workload-zone.sh"
              failOnStderr:            false
              workingDirectory:        "$(System.DefaultWorkingDirectory)"
            displayName:               Deploy SAP Workload Zone
            env:
              ARM_CLIENT_ID:           $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET:       $(ARM_CLIENT_SECRET)
              ARM_OBJECT_ID:           $(ARM_OBJECT_ID)
              ARM_SUBSCRIPTION_ID:     $(ARM_SUBSCRIPTION_ID)
              ARM_TENANT_ID:           $(ARM_TENANT_ID)
              ARM_USE_MSI:             $(Use_MSI)
              AZURE_DEVOPS_EXT_PAT:    $(System.AccessToken)
              CONFIG_REPO_PATH:        ${{ parameters.config_repo_path }}/$(Deployment_Configuration_Path)
              DEPLOYER_KEYVAULT:       $(DEPLOYER_KEYVAULT)
              FENCING_SPN_PWD:         $(FENCING_SPN_PWD)
              SAP_AUTOMATION_REPO_PATH: ${{ parameters.sap_automation_repo_path }}
              SYSTEM_ACCESSTOKEN:      $(System.AccessToken)
              TEST_ONLY:               ${{ parameters.test }}
              TF_IN_AUTOMATION:        true
              TF_LOG:                  $(TF_LOG)
              TF_VAR_subscription_id:  $(ARM_SUBSCRIPTION_ID)
              USE_MSI:                 $(Use_MSI)
