# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# /*---------------------------------------------------------------------------8
# |                                                                            |
# |               This pipeline deploys the SAP Infrastructure                 |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

parameters:
  - name:                              sap_system
    displayName:                       "SAP System SID"
    type:                              string
    default:                           X00

  - name:                              workload_zone_name
    displayName:                       "Workload Environment, use the following syntax: ENV-LOCA-VNET"
    type:                              string
    default:                           TEST-SECE-SAP02

  - name:                              sap_automation_repo_path
    displayName:                       The local path on the agent where the sap_automation repo can be found
    type:                              string

  - name:                              config_repo_path
    displayName:                       The local path on the agent where the config repo can be found
    type:                              string

  - name:                              test
    displayName:                       Test deployment without applying the changes
    type:                              boolean

stages:
  - stage:                             Deploy_SAP_infrastructure
    condition:                         and(not(failed()), not(canceled()))
    variables:
      - template:                      variables/03-sap-system-deployment-variables.yaml
        parameters:
          sap_system:                  ${{ parameters.sap_system }}
          workload_zone_name:          ${{ parameters.workload_zone_name }}
          test:                        ${{ parameters.test }}
    displayName:                       Deploy SAP infrastructure
    jobs:
      - job:                           Deploy_SAP_infrastructure
        displayName:                   Deploy SAP infrastructure
        workspace:
          clean:                       all
        steps:
          - template:                  templates\download.yaml
          - task:                      PostBuildCleanup@4
          - task:                      Bash@3
            name:                      ParameterValidation
            displayName:               Parameter Validation
            inputs:
              targetType:              'filePath'
              filePath:                "$(System.DefaultWorkingDirectory)/sap-automation/deploy/scripts/pipeline_scripts/00-validate-credentials.sh"
              failOnStderr:            false
              workingDirectory:        "$(System.DefaultWorkingDirectory)"
            env:
              AZURE_DEVOPS_EXT_PAT:    $(System.AccessToken)
              SYSTEM_COLLECTIONURI:    $(System.CollectionUri)
              SYSTEM_TEAMPROJECT:      $(System.TeamProject)
          - task:                      Bash@3
            inputs:
              targetType:              'filePath'
              filePath:                "$(System.DefaultWorkingDirectory)/sap-automation/deploy/scripts/pipeline_scripts/03-sap-system-deployment.sh"
              failOnStderr:            false
              workingDirectory:        "$(System.DefaultWorkingDirectory)"
            displayName:               Deploy_SAP_infrastructure
            env:

              APPLICATION_CONFIGURATION_ID: $(APPLICATION_CONFIGURATION_ID)
              ARM_CLIENT_ID:                $(ParameterValidation.ARM_CLIENT_ID)
              ARM_CLIENT_SECRET:            $(ParameterValidation.ARM_CLIENT_SECRET)
              ARM_OBJECT_ID:                $(ParameterValidation.ARM_OBJECT_ID)
              ARM_SUBSCRIPTION_ID:          $(ParameterValidation.ARM_SUBSCRIPTION_ID)
              ARM_TENANT_ID:                $(ParameterValidation.ARM_TENANT_ID)
              AZURE_DEVOPS_EXT_PAT:         $(System.AccessToken)
              CONFIG_REPO_PATH:             ${{ parameters.config_repo_path }}/$(Deployment_Configuration_Path)
              CONTROL_PLANE_NAME:           $(CONTROL_PLANE_NAME)
              SAP_AUTOMATION_REPO_PATH:     ${{ parameters.sap_automation_repo_path }}
              SYSTEM_ACCESSTOKEN:           $(System.AccessToken)
              TEST_ONLY:                    ${{ parameters.test }}
              TF_IN_AUTOMATION:             true
              TF_LOG:                       $(TF_LOG)
              USE_MSI:                      $(Use_MSI)
              WORKLOAD_ZONE_NAME:           ${{ parameters.workload_zone_name }}
