---
# /*---------------------------------------------------------------------------8
# |                                                                            |
# |      This pipeline removes the SAP systems, the workload zone (landscape)  |
# |      and the region via ARM resource group deletion.                       |
# |                                                                            |
# |      The pipeline can be used as fallback in case the terraform            |
# |      destroy doesn't remove everything.                                    |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

parameters:
  - name:                              cleanup_sap
    displayName:                       Remove the SAP system
    type:                              boolean
    default:                           true

  - name:                              sap_system
    displayName:                       "SAP System configuration name, use this format: ENV-LOCA-VNET-SID"
    type:                              string
    default:                           DEV-WEEU-SAP01-X00

  - name:                              cleanup_workload_zone
    displayName:                       Remove the SAP workload zone
    type:                              boolean
    default:                           true

  - name:                              workload_zone
    displayName:                       "SAP workload zone configuration name, use this format: ENV-LOCA-VNET-INFRASTRUCTURE"
    type:                              string
    default:                           DEV-WEEU-SAP01-INFRASTRUCTURE

  - name:                              cleanup_control_plane
    displayName:                       Remove the control plane
    type:                              boolean
    default:                           true

  - name:                              deployer
    displayName:                       "Deployer configuration name, use this format: ENV-LOCA-VNET-INFRASTRUCTURE"
    type:                              string
    default:                           MGMT-WEEU-DEP00-INFRASTRUCTURE

  - name:                              library
    displayName:                       "Library configuration name, use this format: ENV-LOCA-SAP_LIBRARY"
    type:                              string
    default:                           MGMT-WEEU-SAP_LIBRARY

  - name:                              workload_environment
    displayName:                       Environment (DEV, QUA, PRD)
    type:                              string
    default:                           DEV

  - name:                              deployer_environment
    displayName:                       Environment (MGMT, ...)
    type:                              string
    default:                           MGMT

  - name:                              sap_automation_repo_path
    displayName:                       The local path on the agent where the sap_automation repo can be found
    type:                              string

  - name:                              config_repo_path
    displayName:                       The local path on the agent where the config repo can be found
    type:                              string

  - name:                              control_plane_connection
    displayName:                       Service Connection Name for Control Plane
    type:                              string
    default:                           Control_Plane_Service_Connection

  - name:                              workload_zone_connection
    displayName:                       Service Connection Name for Workload Zone
    type:                              string

stages:
  - stage:                             Remove_SAP_systems
    displayName:                       Remove SAP System
    condition:                         eq(${{ parameters.cleanup_sap }}, true)
    variables:
      - template:                      variables/11-remover-arm-fallback-variables.yaml
        parameters:
          deployer:                    ${{ parameters.deployer }}
          deployer_environment:        ${{ parameters.deployer_environment }}
          library:                     ${{ parameters.library }}
          sap_system:                  ${{ parameters.sap_system }}
          workload_environment:        ${{ parameters.workload_environment }}
          workload_zone:               ${{ parameters.workload_zone }}
          connection_name:             ${{ parameters.workload_zone_connection }}
    jobs:
      - job:                           Remove_SAP_system_RG
        displayName:                   Remove SAP System ${{ parameters.cleanup_sap }}
        variables:
          - group:                     SDAF-${{ parameters.workload_environment }}
        steps:
          - task:                      AzureResourceManagerTemplateDeployment@3
            displayName:               Remove Resource Group $(sap_system_foldername)
            inputs:
              deploymentScope:                "Resource Group"
              azureResourceManagerConnection: ${{ parameters.workload_zone_connection }}
              subscriptionId:                 "$(ARM_SUBSCRIPTION_ID)"
              action:                         "DeleteRG"
              resourceGroupName:              "$(sap_system_foldername)"

      - job:                           Remove_sap_deployment_artifacts_in_WORKSPACES
        displayName:                   Remove SAP System deployment artifacts from WORKSPACES
        variables:
          - group:                     SDAF-${{ parameters.workload_environment }}
        steps:
          - template:                  templates\download.yaml
          - bash: |
              #!/bin/bash
              green="\e[1;32m" ; reset="\e[0m"

              echo -e "$green--- Adding deployment automation configuration to devops repository ---$reset"
                cd "$CONFIG_REPO_PATH"  || exit
                git config --global user.email "$(Build.RequestedForEmail)"
                git config --global user.name "$(Build.RequestedFor)"
                git checkout -q $(Branch)
                git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" pull

                echo "##vso[build.updatebuildnumber]Removing $(sap_system_foldername)"

                changed=0
                if [ -d "SYSTEM/$(sap_system_foldername)/.terraform" ]; then
                  git rm -q  --ignore-unmatch -r "SYSTEM/$(sap_system_foldername)/.terraform"
                  changed=1
                fi
                if [ -f  "SYSTEM/$(sap_system_foldername)/sap-parameters.yaml" ]; then
                  git rm -q  --ignore-unmatch "SYSTEM/$(sap_system_foldername)/sap-parameters.yaml"
                  changed=1
                fi

                if [ $(ls SYSTEM/$(sap_system_foldername)/*_hosts.yaml | wc -l ) -gt 0 ] ; then
                  git rm -q  --ignore-unmatch   SYSTEM/$(sap_system_foldername)/*_hosts.yaml
                  changed=1
                fi

                if [ $(ls SYSTEM/$(sap_system_foldername)/*.md | wc -l ) -gt 0 ] ; then
                  git rm -q  --ignore-unmatch   SYSTEM/$(sap_system_foldername)/*.md
                  changed=1
                fi

                if [ $(ls SYSTEM/$(sap_system_foldername)/logs/*.zip | wc -l ) -gt 0 ] ; then
                  git rm -q   --ignore-unmatch  SYSTEM/$(sap_system_foldername)/logs/*.zip
                  changed=1
                fi

                if [ 1 == $changed ]; then
                  git commit -m "Removed filed from devops deployment $(Build.DefinitionName) [skip ci]"
                  git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push
                fi

            displayName:               Remove SAP System deployment artifacts from WORKSPACES
            env:
              SYSTEM_ACCESSTOKEN:      $(System.AccessToken)
            failOnStderr:              false

  - stage:                             Remove_SAP_workload_zone
    displayName:                       Remove SAP workload zone
    condition:                         eq(${{ parameters.cleanup_workload_zone }}, true)
    variables:
      - template:                      variables/11-remover-arm-fallback-variables.yaml
        parameters:
          deployer:                    ${{ parameters.deployer }}
          deployer_environment:        ${{ parameters.deployer_environment }}
          library:                     ${{ parameters.library }}
          sap_system:                  ${{ parameters.sap_system }}
          workload_environment:        ${{ parameters.workload_environment }}
          workload_zone:               ${{ parameters.workload_zone }}
          connection_name:             ${{ parameters.workload_zone_connection }}
          SAP_AUTOMATION_REPO_PATH:    ${{ parameters.sap_automation_repo_path }}
          CONFIG_REPO_PATH:            ${{ parameters.config_repo_path }}/$(Deployment_Configuration_Path)
    jobs:
      - job:                           Remove_SAP_workload_zone
        displayName:                   Remove SAP workload zone ${{ parameters.cleanup_workload_zone }}
        variables:
          - group:                     SDAF-${{ parameters.workload_environment }}
        steps:
          - task:                      AzureResourceManagerTemplateDeployment@3
            displayName:               Remove Resource Group
            inputs:
              deploymentScope:                "Resource Group"
              azureResourceManagerConnection: ${{ parameters.workload_zone_connection }}
              subscriptionId:                 "$(ARM_SUBSCRIPTION_ID)"
              action:                         "DeleteRG"
              resourceGroupName:              "$(zone_folder)"

      - job:                           Remove_zone_deployment_artifacts_in_WORKSPACES
        displayName:                   Remove Workload Zone deployment artifacts
        variables:
          - group:                     SDAF-${{ parameters.workload_environment }}
        steps:
          - template:                  templates\download.yaml
          - task:                      PostBuildCleanup@4
          - task:                      Bash@3
            inputs:
              targetType:              'filePath'
              filePath:                "$(System.DefaultWorkingDirectory)/sap-automation/deploy/scripts/pipeline_scripts/11-remover-arm-fallback-workload-zone.sh"
              failOnStderr:            false
              workingDirectory:        "$(System.DefaultWorkingDirectory)"
            displayName:               Remove SAP Workload Zone deployment artifacts from WORKSPACES
            env:
              SAP_AUTOMATION_REPO_PATH: ${{ parameters.sap_automation_repo_path }}
              CONFIG_REPO_PATH:         ${{ parameters.config_repo_path }}/$(Deployment_Configuration_Path)
              SYSTEM_ACCESSTOKEN:      $(System.AccessToken)
            failOnStderr:              false

  - stage:                             Remove_Control_plane
    displayName:                       Remove Control Plane
    condition:                         eq(${{ parameters.cleanup_control_plane }}, true)

    variables:
      - template:                      variables/11-remover-arm-fallback-variables.yaml
        parameters:
          deployer:                    ${{ parameters.deployer }}
          deployer_environment:        ${{ parameters.deployer_environment }}
          library:                     ${{ parameters.library }}
          sap_system:                  ${{ parameters.sap_system }}
          workload_environment:        ${{ parameters.workload_environment }}
          workload_zone:               ${{ parameters.workload_zone }}
          connection_name:             ${{ parameters.control_plane_connection }}
    jobs:
      - job:                           Remove_control_plane_deployment
        displayName:                   Remove Control Plane deployment
        variables:
          - group:                     SDAF-${{ parameters.deployer_environment }}
        steps:
          - template:                  templates\download.yaml
          - task:                      PostBuildCleanup@4
          - task:                      AzureCLI@2
            continueOnError:           false
            inputs:
              azureSubscription:       ${{ parameters.control_plane_connection }}
              scriptType:              bash
              scriptLocation:          'scriptPath'
              scriptPath:              "$(System.DefaultWorkingDirectory)/sap-automation/deploy/scripts/pipeline_scripts/11-remover-arm-fallback-control-plane.sh"
              failOnStderr:            false
              workingDirectory:        "$(System.DefaultWorkingDirectory)"
              addSpnToEnvironment:     true
              visibleAzLogin:          false

            displayName:               Remove Control Plane deployment artifacts from WORKSPACES
            env:
              ARM_SUBSCRIPTION_ID:      $(CP_ARM_SUBSCRIPTION_ID)
              SAP_AUTOMATION_REPO_PATH: ${{ parameters.sap_automation_repo_path }}
              CONFIG_REPO_PATH:         ${{ parameters.config_repo_path }}/$(Deployment_Configuration_Path)
              USE_MSI:                  $(Use_MSI)
              PAT:                      $(PAT)
