# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
# /*---------------------------------------------------------------------------8
# |                                                                            |
# |      This pipeline removes the Control Plane via Terraform.                |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

parameters:
  - name:                              deployer
    displayName:                       "Deployer configuration name, use this format: ENV-LOCA-VNET-INFRASTRUCTURE"
    type:                              string
    default:                           MGMT-WEEU-DEP01-INFRASTRUCTURE

  - name:                              library
    displayName:                       "Library configuration name, use this format: ENV-LOCA-SAP_LIBRARY"
    type:                              string
    default:                           MGMT-WEEU-SAP_LIBRARY

  - name:                              control_plane_name
    displayName:                       "Control Plane configuration name, use this format: ENV-LOCA-VNET"
    type:                              string
    default:                           MGMT-WEEU-DEP01

  - name:                              use_deployer
    displayName:                       Run removal on self hosted agent
    type:                              boolean
    default:                           false

  - name:                              sap_automation_repo_path
    displayName:                       The local path on the agent where the sap_automation repo can be found
    type:                              string

  - name:                              config_repo_path
    displayName:                       The local path on the agent where the config repo can be found
    type:                              string

  - name:                              connection_name
    displayName:                       Service Connection Name
    type:                              string

stages:
  - stage:                             Remove_control_plane_remote
    displayName:                       "Control plane removal (on agent)"
    variables:
      - template:                      variables/12-remove-control-plane-variables.yaml
        parameters:
          deployer:                    ${{ parameters.deployer }}
          control_plane_name:          ${{ parameters.control_plane_name }}
          library:                     ${{ parameters.library }}
          use_deployer:                ${{ parameters.use_deployer }}
    pool:
      name:                            $(POOL)
    jobs:
      - job:                           Remove_control_plane_remote
        displayName:                   "Start control plane removal"
        variables:
          - group:                     SDAF-${{ parameters.control_plane_name }}
        workspace:
          clean:                       all
        steps:
          - template:                  templates\download.yaml
          - task:                      PostBuildCleanup@4
          - task:                      Bash@3
            name:                      ParameterValidation
            displayName:               Parameter Validation
            inputs:
              targetType:              'filePath'
              filePath:                "$(System.DefaultWorkingDirectory)/sap-automation/deploy/scripts/pipeline_scripts/00-validate-credentials.sh"
              failOnStderr:            false
              workingDirectory:        "$(System.DefaultWorkingDirectory)"
            env:
              CHECK_ARM_SUBSCRIPTION_ID:  $(ARM_SUBSCRIPTION_ID)
              CHECK_ARM_CLIENT_ID:        $(ARM_CLIENT_ID),
              CHECK_ARM_CLIENT_SECRET:    $(ARM_CLIENT_SECRET)
              CHECK_ARM_TENANT_ID:        $(ARM_TENANT_ID)
              CHECK_ARM_OBJECT_ID:        $(ARM_OBJECT_ID)
          - task:                      Bash@3
            inputs:
              targetType:              'filePath'
              filePath:                "$(System.DefaultWorkingDirectory)/sap-automation/deploy/scripts/pipeline_scripts/12-remove-control-plane.sh"
              failOnStderr:            false
              workingDirectory:        "$(System.DefaultWorkingDirectory)"
            displayName:               Remove control plane
            env:
              APPLICATION_CONFIGURATION_ID: $(APPLICATION_CONFIGURATION_ID)
              ARM_CLIENT_ID:                $(ParameterValidation.ARM_CLIENT_ID)
              ARM_CLIENT_SECRET:            $(ParameterValidation.ARM_CLIENT_SECRET)
              ARM_OBJECT_ID:                $(ParameterValidation.ARM_OBJECT_ID)
              ARM_SUBSCRIPTION_ID:          $(ParameterValidation.ARM_SUBSCRIPTION_ID)
              ARM_TENANT_ID:                $(ParameterValidation.ARM_TENANT_ID)
              AZURE_DEVOPS_EXT_PAT:         $(System.AccessToken)
              CONFIG_REPO_PATH:             ${{ parameters.config_repo_path }}/$(Deployment_Configuration_Path)
              SAP_AUTOMATION_REPO_PATH:     ${{ parameters.sap_automation_repo_path }}
              SYSTEM_ACCESSTOKEN:           $(System.AccessToken)
              TF_IN_AUTOMATION:             true
              TF_LOG:                       $(TF_LOG)
              USE_MSI:                      $(Use_MSI)
              key_vault:                    $(Deployer_Key_Vault)

  - stage:                              Remove_control_plane
    displayName:                        "Finalize control plane removal"
    variables:
      - template:                       variables/12-remove-control-plane-variables.yaml
        parameters:
          deployer:                     ${{ parameters.deployer }}
          control_plane_name:         ${{ parameters.control_plane_name }}
          library:                      ${{ parameters.library }}
          use_deployer:                 ${{ parameters.use_deployer }}
    pool:
      name:                             $(Agent)
    dependsOn:
      - Remove_control_plane_remote
    condition:                          in(dependencies.Remove_control_plane_remote.result, 'Succeeded', 'Skipped')
    jobs:
      - job:                            Remove_control_plane
        displayName:                    "Finalize control plane removal"
        variables:
          - group:                     SDAF-${{ parameters.control_plane_name }}
        workspace:
          clean:                       all
        steps:
          - template:                  templates\download.yaml
            parameters:
              getLatestFromBranch:     true
          - task:                      PostBuildCleanup@4
          - task:                      AzureCLI@2
            continueOnError:           false
            inputs:
              azureSubscription:       ${{parameters.connection_name}}
              scriptType:              bash
              scriptLocation:          'scriptPath'
              scriptPath:              $(System.DefaultWorkingDirectory)/sap-automation/deploy/scripts/pipeline_scripts/12-remove-control-plane-finalizes.sh
              addSpnToEnvironment:     true
              visibleAzLogin:          false
              failOnStandardError:     false

            displayName:               Remove control plane
            env:
              SYSTEM_ACCESSTOKEN:       $(System.AccessToken)
              SAP_AUTOMATION_REPO_PATH: ${{ parameters.sap_automation_repo_path }}
              CONFIG_REPO_PATH:         ${{ parameters.config_repo_path }}/$(Deployment_Configuration_Path)
              key_vault:                $(Deployer_Key_Vault)
              TF_IN_AUTOMATION:         true
              TF_LOG:                   $(TF_LOG)
              USE_MSI:                  $(Use_MSI)
              AZURE_DEVOPS_EXT_PAT:     $(System.AccessToken)
