---
name:                                  Create Deployer Configuration

parameters:
  - name:                              control_plane_name
    displayName:                       Deployer Environment name (MGMT, DEV, QA, PRD, ...)
    type:                              string
    default:                           MGMT-NOEU-DEP01

  - name:                              workload_zone_name
    displayName:                       Workload zone name (MGMT, DEV, QA, PRD, ...)
    type:                              string
    default:                           MGMT-NOEU-DEP01

  - name:                              firewall
    displayName:                       Deploy Azure Firewall
    type:                              boolean
    default:                           true

  - name:                              bastion
    displayName:                       Deploy Azure Bastion Service
    type:                              boolean
    default:                           true

  - name:                              webapp
    displayName:                       Deploy SDAF Web App
    type:                              boolean
    default:                           true

  - name:                              deployer_count
    displayName:                       Number of deployers to deploy
    type:                              number
    default:                           1

  - name:                              address_prefix
    displayName:                       Address prefix for the management network
    type:                              string
    default:                           10.170.20


  - name:                              identity
    displayName:                       Use a Service Principal for deployments (legacy), unchecking will use a Managed Identity.
    type:                              boolean
    default:                           false

  - name:                              msi_identity
    displayName:                       Provide the Azure resource identifier for the Managed Identity MSI to use (optional)
    type:                              string
    default:                           ' '

variables:
  - name:                              control_plane_name
    value:                             ${{ parameters.control_plane_name }}

  - name:                              workload_environment
    value:                             ${{ parameters.workload_zone_name }}

  - name:                              deployer_folder
    value:                             ${{ format('{0}-DEP01-INFRASTRUCTURE', parameters.control_plane_name) }}

  - name:                              deployer_file
    value:                             ${{ format('{0}-INFRASTRUCTURE.tfvars', parameters.control_plane_name) }}

  - name:                              library_folder
    value:                             $[format('{0}-{1}-SAP_LIBRARY', split('${{ parameters.control_plane_name }}', '-')[0], split('${{ parameters.control_plane_name }}', '-')[1])]

  - name:                              library_file
    value:                             $[format('{0}-{1}-SAP_LIBRARY.tfvars', split('${{ parameters.control_plane_name }}', '-')[0], split('${{ parameters.control_plane_name }}', '-')[1])]

  - name:                              deployer_region
    value:                             $[split('${{ parameters.control_plane_name }}', '-')[1]]

  - name:                              deployer_environment
    value:                             $[split('${{ parameters.control_plane_name }}', '-')[0]]

  - name:                              deployer_management_network_logical_name
    value:                             $[split('${{ parameters.control_plane_name }}', '-')[2]]

  - name:                              deploy_firewall
    value:                             ${{ format('firewall_deployment                       = {0}', lower(parameters.firewall)) }}

  - name:                              deploy_bastion
    value:                             ${{ format('bastion_deployment                        = {0}', lower(parameters.bastion)) }}

  - name:                              deploy_webapp
    value:                             ${{ format('use_webapp                                = {0}', lower(parameters.webapp)) }}

  - name:                              deployer_count
    value:                             ${{ format('deployer_count                            = {0}', parameters.deployer_count) }}
                                                   public_network_access_enabled             = false

  - name:                              use_spn
    value:                             ${{ format('use_spn                                   = {0}', lower(parameters.identity)) }}

  - name:                              calculated_dns
    value:                             ${{ format('azure.{0}.sdaf.contoso.net', lower(split('${{ parameters.control_plane_name }}', '-')[1])) }}

  - name:                              msi_identity_id
    value:                             ${{ parameters.msi_identity }}

  - name:                              address_prefix
    value:                             ${{ parameters.address_prefix }}

trigger:                               none

stages:
  - stage:                             Create_Configuration
    displayName:                       Create Deployer Configuration
    jobs:
      - job:                           Create_Deployer_Configuration
        displayName:                   Create Deployer Configuration
        workspace:
          clean:                       all
        steps:
          - task:                      PostBuildCleanup@4
          - checkout:                  self
            persistCredentials:        true
          - template:                  templates\download.yaml
            parameters:
              getLatestFromBranch:     true
          - task:                      PowerShell@2
            displayName:               "Create Sample"
            inputs:
              targetType:              "inline"
              filePath:                "$(System.DefaultWorkingDirectory)/sap-automation/deploy/scripts/pipeline_scripts/22-sample-deployer-configuration.ps1"
              failOnStderr:            false
              showWarnings:            true
              pwsh:                    true
