# /*---------------------------------------------------------------------------8
# |                                                                            |
# |     This workflow validates the Terraform Syntax      |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

name: 'Validate Terraform'
on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*.*"
  pull_request:
    branches:
      - "release/*"
permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform Validation'
    runs-on: ubuntu-latest
    environment: test

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name:                                     Checkout repository
      uses:                                     actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth:                            0
        token:                                  ${{ secrets.GITHUB_TOKEN }}

    - name:                                     Configure Git Safe Directory
      run:                                      |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git config --global --add safe.directory "/__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}"


    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Initialize a new Terraform working directory by creating initial files.
    - name: Terraform Init SAP Deployer (bootstrap)
      run: terraform -chdir="deploy/terraform/bootstrap/sap_deployer" init -backend=false

    # Checks that all Terraform configuration files validate
    - name: Terraform Validate SAP Deployer (bootstrap)
      run: terraform -chdir="deploy/terraform/bootstrap/sap_deployer" validate


    # Initialize a new Terraform working directory by creating initial files.
    - name: Terraform Init SAP Library (bootstrap)
      run: terraform -chdir="deploy/terraform/bootstrap/sap_library" init -backend=false

    # Checks that all Terraform configuration files validate
    - name: Terraform Validate SAP Library (bootstrap)
      run: terraform -chdir="deploy/terraform/bootstrap/sap_library" validate

    # Initialize a new Terraform working directory by creating initial files.
    - name: Terraform Init SAP Deployer (run)
      run: terraform -chdir="deploy/terraform/run/sap_deployer" init -backend=false

    # Checks that all Terraform configuration files validate
    - name: Terraform Validate SAP Deployer (run)
      run: terraform -chdir="deploy/terraform/run/sap_deployer" validate


    # Initialize a new Terraform working directory by creating initial files.
    - name: Terraform Init SAP Library (run)
      run: terraform -chdir="deploy/terraform/run/sap_library" init -backend=false

    # Checks that all Terraform configuration files validate
    - name: Terraform Validate SAP Library (run)
      run: terraform -chdir="deploy/terraform/run/sap_library" validate

    # Initialize a new Terraform working directory by creating initial files.
    - name: Terraform Init SAP Workload Zone
      run: terraform -chdir="deploy/terraform/run/sap_landscape" init -backend=false

    # Checks that all Terraform configuration files validate
    - name: Terraform Validate SAP Workload Zone
      run: terraform -chdir="deploy/terraform/run/sap_landscape" validate

    # Initialize a new Terraform working directory by creating initial files.
    - name: Terraform Init SAP System
      run: terraform -chdir="deploy/terraform/run/sap_system" init -backend=false

    # Checks that all Terraform configuration files validate
    - name: Terraform Validate SAP System
      run: terraform -chdir="deploy/terraform/run/sap_system" validate
