---
name: trivy

on:
  pull_request:
    types: [ 'opened', 'reopened', 'synchronize' ]
  merge_group:
  workflow_dispatch:


permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  build:
    name: 'trivy scan'
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
      with:
        egress-policy: audit

    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Run Trivy vulnerability scanner (file system)
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        scan-ref: .
        format: 'sarif'
        scanners: 'vuln,secret,config'
        output: report-fs.sarif

    - name: Upload Trivy report (fs) GitHub Security
      uses: github/codeql-action/upload-sarif@76621b61decf072c1cee8dd1ce2d2a82d33c17ed # v3.29.8
      with:
        sarif_file: report-fs.sarif
        category: 'fs'
